### ISSUE TITLE
Use CB API

### ISSUE THREAD

**Issue by zoopzorp** [jrudess/streamdvr#1]
The other version of your script used the API and that seemed better as when you're following 100+ models that's a lot of HTTP requests to hit CB with every minute. Are there any plans to include the API for online model checking in this version?

Thanks

edit: This looks like it was taken out in commit 79ab431 10 days ago. Were there issues with it?

**Comment by jrudess** [comment]
The new CB json interface versus the old scraping method  is a permanent plan as part of jrudess/mfc_cb.node#35.   The JSON api provides better information, and is easier to parse, debug, and maintain in the code.

You can use the batchSizeCB option in config.yml to slow down the fetches (smaller values throttle it) if you're worr\ied about too many requests too quickly.  But I don't recommend setting the scan interval as low as 60s, especially with such a large list.
