### ISSUE TITLE
[Request] RTMP Support

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#10]
Since the old repository has been deprecated, I want to reopen this https://github.com/jrudess/mfc_cb.node/issues/27 again.

my last reply on the above:

Myfreecams with rtmp option: https://github.com/horacio9a/mfc-node would love to see a universal version though as rtmp with this script is for windows (not tested by myself). its the only script available to the publlic that supports rtmp for MFC. sstativa does have rtmp version of mfc-node but its not available for public. 

Chaturbate: https://github.com/horacio9a/capturebate-node but it needs login. from experience after certain period it blocks you from signing in from browser and it doesn't detect all models being followed. also i have noticed that newly followed models dont record for some reason either. alternative option is https://github.com/horacio9a/chaturbate-anonymous but it records single model at anytime so if you want to record multiple models then you need to run multiple instances of the script. its much more realiable then the above though

Overall IMO i think its easier to add support for chaturbate then it is for myfreecams but MFC needs it more since there is always problems with their streams which i believe (heard) can only be fixed via rtmp.

**Comment by jrudess** [comment]
I've read a bit through horacio9a's code and unfortunately it relies on some 'MFCD.exe' program that looks like it may have been removed from github.   But it wouldn't work in linux, so it's not really an option for me.  

However, I'm a bit interested in having some rtmp support in streamdvr myself, and am looking into various solutions.

**Comment by jrudess** [comment]
I think this is not something I will ever implement.  If someone came with a pull-request, I would probably accept it though.
