### ISSUE TITLE
Query: How do you maintain your streamer list?

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#100]
I'm not a big fan of the current configuration system with 2 yml files per site.   Largely this flow has remained in place since mfc_cb.node, because I haven't decided on a better system.  This issue is to gauge how people are using the site_updates.yml files:

Do you...

1) add/remove streamers by editing  site_updates.yml manually?
2) add/remove streamers by editing site.yml manually (when streamdvr is not running)?
3) use the CLI to add/remove streamers (when ```tui: true``` is set)?
4) use a program or script to add/remove streamers by automatically modifying site_updates.yml?

**Comment by Asynchr0nous** [comment]
I personally use option 1. not sure how or why you would use option 2 since that would break the script (its the common script amost all sites) and it doesnt make sense to either. i been thiinking about comand line based removal without enabling tui but not sure if thats possible.

ideally something along the lines of:

```

> add site model (if more than 1 more than you could either enter on newline or on single single lise below)
> model 
> model 
> model
> rm site model (here it removes model based of keyword rm and anything after this keyword will be removed form list. order of removal and additional don't matter as long as it detects these two words)

```

That being said nothing is more bullet proof than the existing method of having two files per site (though i do agree it gets too much as number of supported sites increase)

**Comment by Ptibouc77** [comment]
Option 2 and sometimes 1

**Comment by Hampster82** [comment]
Typically option 1.

One of the older node scripts I used back in the day had a web interface (which I never used), but the actual command to add or remove was also possible to just type in the browser address bar, that was pretty handy. It was something simple like this.
>http://localhost:9082/streamers/include?uid=1234567890
>http://localhost:9082/streamers/exclude?uid=1234567890

So I could just start typing either include or exclude, use arrow keys to pick the full address and replace the id before hitting enter. A lot more convenient than what we have now I think.

**Comment by Asynchr0nous** [comment]
i still use this script use speak of...horacio9a's mfc-node uses that implementation and pusspounder's

**Comment by nerdydude** [comment]
When the script is running I will use option 3, but when I occasionally restart it, I will use option 2.  I do option 2, because it allows me to keep the names of models as comments next to their uid number and comment out some names in my yml file.

**Comment by jrudess** [comment]
@nerdydude yeah, I really don't like the way the yml libraries are used currently, because comments get stripped when the yml is loaded, so any save actions re-write the file without comments.

**Comment by nerdydude** [comment]
@jrudess  Yeah. It sucks, but I get around it by having my configs committed. I just revert them if I use option 3, but mostly I use addtemp instead of add. Also my configs rarely change these days.

**Comment by forsomefun2** [comment]
You deleted my comment but my old recorder had the ability to add in MFC models from the names only. Other sites just use the name.

**Comment by jrudess** [comment]
@forsomefun2 streamdvr already has the ability to add MFC models by name using either mfc_update.yml, or the TUI command line: ```add mfc streamername```

**Comment by forsomefun2** [comment]
Yeah I think you improved it last time I check it didn't work very well since getting the names requires MFCAuto

**Comment by jrudess** [comment]
Ah yes, the name lookup does still require MFCAuto, and that was busted for quite a while -- you're definitely right about no native lookup code anymore.

With the most recent commit, the TUI is a bit more efficient with redrawing and calculating the streamer list pane.  Also should fix a bug with lists > ~300 in size.

However, the streamer-list is probably not very useable though with such large lists as it displays everyone, both online and offline, so you'd constantly have to scroll (press 1 to focus it, pgup/pgdown to scroll).  

But I plan to add a toggle so that the list only shows streamers that are online, to serve as a viewable dashboard for larger lists.
