### ISSUE TITLE
streamdvr breaks if capture/complete directories have spaces

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#102]
i'm not sure what exactly i'm doing wrong but it just constantly says `model is streaming,
recording started, model_20181127_184706.ts not found in capturing directory, cannot convert to null`
this is using with both using youtube-dl/streamlink for fetching and streamlink/ffmpeg for recording.

Update:

Upon looking at log files it seems like some kind of error with directory  when using youtube-dl for fetching : `Unable to find a suitable output format for '/Volumes/Passport'
/Volumes/Passport: Invalid argument` so here i think whats happening is its able to fetch the url but cant start recording because it can't find "/volume/passport ultra" because of the space.  this is also the case for mfc which doesn't reply on bash scripts. not sure what has changed because this has always been my drive name

looks like some bug in m3u8_streamlink.sh as the log file says: `usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: best` but it does detect model is streaming but no recorder log get produced because it doesn;t actually fetch the url. i tried moving position of "best" including putting it quotes but not being able to get it to work

finally i thought this was causing the above issues so removed server from config file even though i have proxy set to false: `running: scripts/m3u8_streamlink.sh https://www.chaturbate.com/model 0 socks5://127.0.0.1:1080` but this command works fine from terminal

**Comment by jrudess** [comment]
I have some theories as to why a space in the directory name would break things, and will investigate.

**Comment by Asynchr0nous** [comment]
if it helps in python i generally put quotes around directories to avoid this exact issue e.g. `'"{}"'.format(captureDirectory)`

javscript equivalent i found is this https://stackoverflow.com/questions/9714759/put-quotes-around-a-variable-string-in-javascript and https://stackoverflow.com/questions/44795264/add-double-quotes-to-string-which-is-stored-in-variable

**Comment by jrudess** [comment]
Not a correct fix.   Will look into this more as time allows.

**Comment by jrudess** [comment]
Still working on this one.  Nothing that I think should work seems to (escapes, quotes, etc).   I can copy/paste the exact command I'm running from the logs and it works in the shell, but node's spawn() fails.  On the plus side, learning a lot of bash stuff and the scripts are slightly cleaner as a result.

**Comment by jrudess** [comment]
Using softlinks to avoid the paths with spaces as a workaround is all I can recommend trying at the moment.   I'll definitely get this fixed, but may end up reworking some of the flows a bit in order to do so if I can't find an elegant solution.

**Comment by Asynchr0nous** [comment]
i'm still trying to figure what has changed that it doesn't recognise the drive i've been using for ages.

**Comment by Asynchr0nous** [comment]
after having a look at my personal script for editing videos i managed to fix this issue. you need to put quotes around `$output` in "record_ffmpeg.sh". so the full command is should be:

> ffmpeg -hide_banner -i $url -c copy -vsync 2 -r 60 -b:v 500k $extraargs $debugargs "$output" &

the site.js does not need editing at all

**Comment by Asynchr0nous** [comment]
`

**Comment by jrudess** [comment]
Awesome, confirmed that this fixes it for me as well.
