### ISSUE TITLE
MFC stops working after a couple of days and needs restarting

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#104]
So I'd say this happens once every 2-3 days. Once all MFC captures are done, MFC no longer finds new models to capture even though they're online. I'll enable all debug logging and see if anything comes out of it. This is with MFCAuto v5.6.2.

**Comment by jrudess** [comment]
Yeah, its definitely happened to me as well.  One mitigation technique I've been considered is to periodically destroy and re-create the MFCAuto object when no one is being recorded, forcing a reconnect.

**Comment by PurrSevere** [comment]
My thoughts exactly. That should fix things up for the time being.

**Comment by Hampster82** [comment]
Yeah, I've noticed this too.
I set up a secondary backup capture with sstativa's fork of mfc-node with rtmp support to see how it behaves, and I noticed that whatever happens, it also stops all captures in there, but that script will always reconnect on the next cycle whereas streamdvr doesn't.
It use mfcauto as well.

I haven't tested how the ffmpeg version of that same script behaves however. I should test that at some point.

**Comment by PurrSevere** [comment]
This seems to be happening more frequently now. I'd say it's somewhere between 10-12 hours now.

**Comment by Hampster82** [comment]
I'm not sure the commit fully fixed this. This still occasionally happens on my end at least. Does it only happen on single site or is it a wider script problem?

**Comment by PurrSevere** [comment]
Tried the updated version. The most it lasted was 34 hours before having to restart.

**Comment by forsomefun2** [comment]
I missed out on the updated version

I'm just using jobber to restart streamdvr every day at a specific time like 6 am .

**Comment by Hampster82** [comment]
Has this been fixed in the commits in the past 3 or so months? I haven't updated in a while.

**Comment by PurrSevere** [comment]
It's a lot better than it used to be. It has happened a couple times since the update but it's very rare now.

**Comment by PurrSevere** [comment]
It looks like MFC changed some things around recently because It seems to be having an unstable connection to MFC. If I add a model to be included/excluded in the mfc_updates.yml, streamdvr doesn't see the changes. Sometimes it will see the changes at random times but that can be from 30 minutes to a couple hours even though the refresh time is set to every 5 minutes. 

If I add a model to be included/excluded in any other site_updates.yml file that uses the basic.js plugin, it works normally. 

I have tried this with various versions starting from v0.12.0 to the latest commit 608fbb9.
