### ISSUE TITLE
[Help Wanted] How to modify captureArgument?

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#105]
I still use your older script for models that stream in 720p or less for two reasons, firstly because my list is quite big when compared with others and secondly it allows me to split this list so that i can use streamlink for models that stream in 720p or above (to limit it 720p). this somewhat keeps cpu usage lower than if i were to move completely to either streamlink/youtube-dl. however one issue with this is that i can’t always select the highest stream and also limit it to 720p. 

Solution:
I was looking at your code earlier to understand how it works and came across the “$” sign you used in .sh script to get output of something and store it in a variable. In all of the versions released (excluding the latest), this line of code in site.js has always been the same:

```
params = [
                "-hide_banner",
                "-v",
                "fatal",
                "-i",
                url,
                "-c",
                "copy",
                "-vsync",
                "2",
                "-r",
                "60",
                "-b:v",
                "500k",
                this.config.captureDirectory + "/" + filename + ".ts"
            ];
```

i tried running the above params directly in terminal and replaced the `url` with `$(command)` so the full command becomes 

`ffmpeg -hide_banner -v fatal -i  $(streamlink --stream-url https://edge141.stream.highwebmedia.com/live-hls/amlst:fut8nari-sd-4466e544128c50a3c02381a9bba8bb1602e6f8b642627ccb91e6fc83480b01c2_trns_h264/playlist.m3u8 best --stream-sorting-excludes=1080p)  -c copy -vsync 2 -r 60 -b:v 500k filename.ts` 
^^this works perfectly (could try it now since shes online)

replaced `url` in "params"  with this: ``$(streamlink --stream-url ${url} worst --stream-sorting-excludes>720p)`` in site.js and it just says recording started, not found in capturing directory.  

Any help is appeciated
Edit: ` sign doesn't show on here but i've included before the dollar sign and after

**Comment by nerdydude** [comment]
I am not sure how to solve your problem, but the problem with what you posted here:

> ffmpeg -hide_banner -v fatal -i $(streamlink --stream-url https://edge141.stream.highwebmedia.com/live-hls/amlst:fut8nari-sd-4466e544128c50a3c02381a9bba8bb1602e6f8b642627ccb91e6fc83480b01c2_trns_h264/playlist.m3u8 best --stream-sorting-excludes=1080p) -c copy -vsync 2 -r 60 -b:v 500k filename.ts

Is that you are passing streamlink to ffmpeg, but streamlink doesn't return anything normally.  You may want to try the -O flag on the streamlink command. That flag will output the stream to the command line, which ffmpeg may be able to pick up, but I am not sure.

**Comment by jrudess** [comment]
The --stream-url switch causes streamlink to output only the URL to the m3u8, so on the surface I think that would work.

As to why you get an error, I think it is your attempt to say >720p.   The command line argument only is an assignment with a separator list, so I think you'd have to say something like --stream-sorting-excludes=960p,1080p

And any time a new weird thing happens, then you get to update it. :-)

But it is possible to get the behavior of checking for >720p, but it means a bunch of shell script code to query the site for all the candidates, then do your own filtering to build up an 'excludes' list.

**Comment by Asynchr0nous** [comment]
@jrudess  sorry the --stream-sorting-excludes>720p was supposed to be --stream-sorting-excludes=1080. the full command i pasted above  was actually was from the script itself. it works if I use it in directly in terminal but not through "spawn".  if you replace playlistUrl with url of any live model, it will start recording.

`ffmpeg -hide_banner -v fatal -i  $(streamlink --stream-url playlistUrl best --stream-sorting-excludes=1080p)  -c copy -vsync 2 -r 60 -b:v 500k capturing/modelName.ts
`

**Comment by Asynchr0nous** [comment]
@nerdydude i'm not sure where to the  -O flag but the dollar sign you see after "-i" means get the output of the command (in my case get the output of streamlink) and pass it to ffmpeg. it runs that command before it makes an attempt at copying video stream etc

**Comment by jrudess** [comment]
My apologies, I'm a bit confused on this issue.   I added {shell: true} to 'startCapture()' in site.js, and I don't see any difference in log outputs.  What does this change provide over the current flow?
