### ISSUE TITLE
killarg="" # Note: Streamlink does not respond to SIGINT 

### ISSUE THREAD

**Issue by kuchenstrudel** [jrudess/streamdvr#107]
Streamlink seems to respond to SIGINT just fine, at least in my testings. See example below.

1. ```streamlink -o test.mkv https://www.twitch.tv/$random_twitch_streamer best```

```[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/$random_twitch_streamer best
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[download][test.mkv] Written 4.7 MB (12s @ 403.0 KB/s)
```

2. ```kill -INT $PID```
```[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

**Comment by jrudess** [comment]
Interesting.   If I add -INT then the streamlink jobs never die, and I'm also unable to kill them manually from the shell unless I use sigterm.   

Will investigate it more.   I'm currently on 0.14.2.r150.g649f483a which looks like its only 7 commits behind the master branch.

**Comment by kuchenstrudel** [comment]
I'm using 0.14.2 from the package manager. Maybe node `kill` is different?

**Comment by jrudess** [comment]
I can't kill the streamlink processes from node or from outside in the shell either with SIGINT.  Will downgrade to 0.14.2 release to see if its a newly introduced issue.

**Comment by jrudess** [comment]
I installed the package release instead of git repo, and at least on my arch system, streamlink never responds to 'kill -INT'.

Although, from googling around it seems that maybe on some systems it would have to be kill -SIGINT.  So maybe its safer to just make it kill -2, as that looks like its constant.
