### ISSUE TITLE
Future TUI ideas

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#108]
List of TUI ideas as I think of them.  Feel free to post your own.   Most of the core code for any TUI features will apply to a future web-interface.

- [x] Identify temporary recordings uniquely in streamer list
- [x] Allow cursor navigation of streamer list with popup menu when selecting entries:
  * Sites
    - [x] Add Streamer
    - [x] Pause/Unpause site
    - [x] Enable/Disable Site
  * Streamer:
    - [x] Toggle to only show online streamers
    - [x] Pause/Unpause streamer
      - [x] Duration for pause (optional)
      - [x] Pause state persists on reload
    - [x] Remove streamer
- [ ] When ```debugrecorder: true```, log pane shows live recorder output when streamer is active selection.
- [ ] Live filter log pane to a selected site, or selected streamer.

**Comment by rarandom** [comment]
It would be neat if `pause`/`unpause` commands could take a duration as optional parameter. After that time has elapsed, it would automatically revert to the previous state. This would also be useful (perhaps even more so) for the `addtemp` command.

It'd also be great if paused/unpaused state persisted through restarts of the script.

**Comment by jrudess** [comment]
@rarandom All good suggestions, thanks!

**Comment by jrudess** [comment]
@rarandom Added an optional timer to pause command.  This only works when pausing an individual streamer, and not for pausing an entire site.  The unpause command has been removed and 'pause' is now a toggle.

To record someone for only 30s:
```
pause site streamer
pause site streamer 30
```

To pause someone for only 30s:
```
pause site streamer 30
```

**Comment by camjac251** [comment]
Would it be possible to add Webhooks check support for Twitch? That way interval checks can be avoided with a large number of users. I've gotten time out errors from the Twitch API through interval checks and it has ended other scripts (haven't tested streamdvr)
https://dev.twitch.tv/docs/api/webhooks-reference/#topic-stream-changed
https://github.com/mtverlee/lars/issues/13

**Comment by jrudess** [comment]
@camjac251 I stick to a 5 minute polling check, and only polling 3-4 streamers on twitch, so no bans, but I can see that with a large list or a short polling timer, you could get timed-out, or even IP banned.

It is possible to extend the Basic plugin to implement the twitch-api specific hooks you're interested in though it is not something I'm likely to look into for quite some time, but pull-requests are welcome.

**Comment by camjac251** [comment]
To extend the webhooks feature request, would it be possible to support a metadata file saved alongside the stream containing the different titles during stream, twitch category changes, viewcount peak?
It seems available through the API, maybe even a better way of checking if someone is online as well
https://dev.twitch.tv/docs/api/reference/#get-streams
https://discuss.dev.twitch.tv/t/webhook-twitch-start/21010

**Comment by jrudess** [comment]
I have no more plans to implement the final two debug hooks to show live recorder output in the log pane.   The files exist on disk and can be 'tail'ed to monitor the output during debug sessions, so there's very little value in having it done in the TUI.
