### ISSUE TITLE
the 960p issue

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#110]
every other day one of my recordings were being recorded in 960p despite the fact i explicitly excluded it using streamlink (for others using ffmpeg's -map). well i was testing something and it turns out the reason for that was unlike your normal resolutions like 720p etc, mfc sometimes has these weird resolutions like`5564k` which represents 960p or `614k` for 240p etc.

this might also explain why some users had to use slightly different ffmpeg mapping command to avoid this issue. i've seen these resolutions before but it never was an issue back then

**Comment by jrudess** [comment]
Awesome, thanks for the info.   It sounds like I should add 5564k to the excludes list.   Let me know if that helps for you.
