### ISSUE TITLE
streamdvr quits when "captured" directory exists

### ISSUE THREAD

**Issue by lukiluki123** [jrudess/streamdvr#113]
When "capturing" or "captured" directory exists I get the following error:
>fs.js:909
  return binding.mkdir(pathModule.toNamespacedPath(path),

The solution is very easy, replace `mkdir` function in `dvr.js` with this:
>    mkdir(dir) {
        const fulldir = path.resolve(dir);
        if (!fs.existsSync(fulldir)) {
          fs.mkdirSync(fulldir, {recursive: true}, (err) => {
              if (err) {
                  this.log(err.toString());
                  process.exit(1);
              };
          });
        };
        return fulldir;
    }

**Comment by jrudess** [comment]
I suspect your version of node is too old.  The {recursive: true} option is what allows it to not fail when the directory exists.
