### ISSUE TITLE
Need help how to fix this error?

### ISSUE THREAD

**Issue by Jankz00** [jrudess/streamdvr#126]
WARNING: _handleExtData error: AssertionError [ERR_ASSERTION]: Malformed Message? {"nm":"Abbierose","sid":315300297,"uid":30702170,"vs":0,"pid":1,"lv":4,"u":{"camserv":1349,"phase":"z","chat_color":"FF6EC7","chat_font":4,"chat_opt":641,"creation":1545145502,"avatar":1,"profile":1,"photos":8,"blurb":"Your babygirl"},"m":{"new_model":0,"missmfc":0,"camscore":2636.3,"continent":"NA","flags":80928,"rank":0,"rc":9,"topic":"naked at goal 1135 :) 30 tokens for pole dance :) whiteboard has tip menu :) ask for my snapchat!!!!","hidecs":1},"x":{"share.albums":1,"share.follows":13,"share.clubs":1,"share.tm_album":1548360492,"share.collections":0,"share.stores":15,"share.goals":3,"share.polls":1,"share.things":21,"social.uname":null,"social.posts":null,"social.tm_post":null}} - {"msg":{"arg1":1908,"arg2":21,"from":0,"len":0,"to":1,"type":14},"msglen":574008,"opts":256,"respkey":1592485486,"serv":1506,"type":14} - 'https://www.myfreecams.com/php/FcwExtResp.php?respkey=1592485486&type=14&opts=256&serv=1506&'
        {"count":1907,"op":4,"owner":0,"rdata":[["nm","sid","uid","vs","pid","lv",{"u":[...

**Comment by jrudess** [comment]
Was this a one time event, or do you consistently get this?  MFC recently changed their server protocol, so old versions of MFCAuto may not work anymore.

I've uploaded the latest version here:
https://volafile.org/get/CDBA1fZPwfqgd/MFCAuto.v5.11.4.tar.gz

The link will only be valid for 48 hours.

**Comment by Jankz00** [comment]
happens every time i open the program.. i use the program to cap chaturbate.. sorry for late reply

**Comment by forsomefun2** [comment]
could it be node version?

**Comment by Jankz00** [comment]
no idea how to check that i just run it is all i do

**Comment by jrudess** [comment]
If you aren't using mfc, then you can edit mfc.yml and set "enable: false".

**Comment by Jankz00** [comment]
ok thanks, would i still need the mfcauto?
