### ISSUE TITLE
Planned breaking changes to site.yml formatting

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#128]
In order to support storing more information (such as paused state), I'm making some changes to the site.yml format which will break existing site.yml files.

Old format
```
streamers:
   - streamer1
   - streamer2
```

New format (in flux):
```
streamers:
  - - streamer1_id
    - streamer1_name
    - paused
  - - streamer2_id
    - streamer2_name
    - unpaused
```

For most sites, id and name are identical.   The MFC plugin is the only case where id and name are not the same.

**Comment by forsomefun2** [comment]
Will there be a converter
for just a list i.e 

```
person 1 
person 2 
person 3
```
To the correct formatting?

**Comment by jrudess** [comment]
The implementation for this is done, I just need to run for a couple of days to look for issues.

The lists will be automatically converted from the old format to the new format the first time streamdvr is launched.   However, I strongly recommend you make backups of all your yml files in case there is a bug I didn't catch.

**Comment by jrudess** [comment]
All of the changes are committed to the `development` branch.   I could use some help with testing the feature out, so if you're up for it, please make a backup of all of your yml files and pull the development branch and let me know if you run into any problems with the auto-upgrading of the yml files or capturing of streams.

In order to use the  development branch a new version of the mfc plugin is needed and it is uploaded at https://volafile.org/get/CNJ7KTy6kiBmc/mfc.js

This new version of mfc plugin is NOT compatible with master branch.

**Comment by vcl1** [comment]
The upgrade went well without issues (I only use mfc). Ubuntu 19.04 nodejs 11.14.0

**Comment by SouthernBlackNerd** [comment]
My conversion also went well. Mac Sierra 10.12.6 and node 11.12.0

**Comment by jrudess** [comment]
Thanks guys, appreciate the help testing it out.   mfc.js plugin reuploaded at https://volafile.org/get/CNqUXT7Lz4LVV/mfc.js

Changes merged to master branch.
