### ISSUE TITLE
All streamers showing as 'Offline'

### ISSUE THREAD

**Issue by e2489** [jrudess/streamdvr#135]
I'm on Windows 10 and I've installed WSL (Ubuntu). I have nodejs (v12.2.0) installed via WSL. I've run 'npm install' and it completed without errors. I'm navigating to the /mnt/c/streamdvr folder and running ./streamdvr. It opens and shows the streamers, but all streamers are listed as offline, even though they are not. Using the latest ffmpeg and default config.yml

If I enable the debug options, the only thing I'm seeing for all streamers is:
TWITCH   [DEBUG] shroud running: /mnt/c/streamdvr/scripts/m3u8_youtubedl.sh -s https://www.twitch.tv/shroud

Nothing else and no other errors.

**Comment by jrudess** [comment]
Can you try manually running this command at the prompt and see what it prints?  (replace the streamer with someone that is online) and see what output you get?
```
/mnt/c/streamdvr/scripts/m3u8_streamlink.sh -s https://www.twitch.tv/shroud
```

**Comment by jrudess** [comment]
Also try running streamlink directly:
```
streamlink --stream-url https://www.twitch.tv/shroud best
```

**Comment by e2489** [comment]
Turns out I had neither of those installed. Haven't updated since the change to Linux, and I didn't get that those had to be installed through WSL now instead of just using the files like before. It's working now.

One question I have though, I prefer to just keep the raw .ts files and not convert them. Before, I would just comment out 'autoConvertType'. That works still, but the files are no longer being moved to the 'captured' folder once the recording is done.

**Comment by jrudess** [comment]
instead of commenting it out you should be able to just set the value to 'ts'
```
autoConvertType: ts,
```

**Comment by e2489** [comment]
That worked. Thank you.
