### ISSUE TITLE
Small visual error 

### ISSUE THREAD

**Issue by ghost** [jrudess/streamdvr#136]
stream still seems to be recording I see the files growing in size but
output states

ERROR: Unable to find stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I updated to 2019 5 11 verison of youtube-dl 

Still that error appears. I did  a fresh install of streamdvr today.

**Comment by jrudess** [comment]
Can you post a sanitized version of your config.yml and site.yml?   I haven't been able to replicate this.

**Comment by forsomefun2** [comment]
```
name: CB
plugin: ./lib/plugins/basic
siteUrl: 'https://chaturbate.com/'
urlback: ''
enable: true
m3u8fetch: scripts/m3u8_youtubedl.sh
recorder: scripts/record_streamlink.sh
scanInterval: 300
batchSize: 5
streamers:
  - - 2guud4u
    - unpaused
  - - 8bitdeviants
    - unpaused
  - - adelrudicam
    - unpaused
  - - alexistexas1
    - unpaused
  - - alicemars
    - unpaused
  - - alice_stoned
    - unpaused
  - - allurablackxxx
    - unpaused
```


```
enable:
  daemon: false
recording:
  autoConvertType: mkv
  captureDirectory: /home/xxxxxxx/streamdvr/capturing/
  completeDirectory: /home/xxxxx/google/
  postprocess: "scripts/postprocess_ffmpeg.sh"
  dateFormat: YYYYMMDD_HHmmss
  includeSiteInFile: false
  includeSiteInDir: false
  streamerSubdir: true
  siteSubdir: true
  keepTsFile: false
  minSize: 0
  maxSize: 0
postprocess: ""
log:
  enable: true
  append: true
tui:
  enable: false
  logshown: true
  listshown: true
  allowUnicode: false
colors:
  name: magenta
  state: yellow
  offline: blue
  prompt: blue
  file: green
  time: grey
  site: green
  cmd: grey
  debug: yellow
  error: red
proxy:
  enable: false
  server: socks5://127.0.0.1:1080
debug:
  log: false
  recorder: false
  errortrace: false



```

**Comment by jrudess** [comment]
I think your issue is probably not resolved yet, but can you run the latest commit to see if you are still seeing this problem?

**Comment by jrudess** [comment]
I think I've seen something similar but slightly different with the mfc plugin.   Sometimes mfc will return that a stream is running, but when you try to fetch the URL it doesn't exist.  Either the camserv is having issues, or MFC or even just MFCAuto has a stale state for a little bit.

This results in a spam of attempted recordings, but each one failing.

I've made a release v13.1.  Can you let me know if this is still happening with that version?
