### ISSUE TITLE
Running as service

### ISSUE THREAD

**Issue by camjac251** [jrudess/streamdvr#138]
Is it possible to run this as a service without systemd? Like the process could serve as the service? I've noticed that when a stream ends, the process ends with it. Is this normal behavior? Can I change it so it's an always active service checking for usernames (twitch) going live and when one goes offline, it continues monitoring?

**Comment by jrudess** [comment]
There is an example systemd .service file you can look at in the main directory, but it needs to be filled in by hand.  In `config.yml` you'll want to set the `daemon` option to true and the `tui` option to false.  

My personal flow is to have tmux restore all my terminal sessions on boot using a systemd tmux user service.   One of the tmux windows is an instance of streamdvr with `tui` enabled.

Streamdvr shouldn't exit when a recording stops, but it should keep running so it can record future streams that start.  If the main process exits, it's probably a bug.  You can turn on all the debug options in config.yml.
