### ISSUE TITLE
"Recording appears to be stuck"

### ISSUE THREAD

**Issue by e2489** [jrudess/streamdvr#140]
Every so often I get this message: "_____ recording appears to be stuck (counter=0), file size is not increasing: ___MB"

Followed by "_____ terminating stuck recording"

**Comment by jrudess** [comment]
This means that ffmpeg or streamlink are still running, but the filesize of the recording isn't increasing.   Streamdvr will manually kill the ffmpeg or streamlink process, and then restart the recording.

However, it shouldn't terminate until the counter is 2.   Will look into it.

**Comment by jrudess** [comment]
I don't see any issue with the counter, so I'm guessing the log paste isn't complete and there was a print out showing "counter =  1" as well.

My recommendation is to make sure you have a recent version of ffmpeg if you are using it to record (i.e. 4.1.x).  The default version of ffmpeg from various distribution package managers can be quite old.

**Comment by jrudess** [comment]
Saw something similar to this happen for a case where the record loop for the site was running twice.   First call to the size-check routine is fine, but it updates the current-size, so the second record-loop is at the same size and then thinks the recording is stuck.

**Comment by e2489** [comment]
Ok, it actually looks like what's happening is the streamer is ending their stream when this happens but streamdvr doesn't recognize that, and instead thinks the recording is stuck. This doesn't seem to be having any adverse effects (and I don't see the error most of the time), but that's what's going on.
