### ISSUE TITLE
CB recordings only 11 minutes

### ISSUE THREAD

**Issue by ghost** [jrudess/streamdvr#143]
Not sure what going on but it seems a lot of CB recordings are stopping after 11 minutes.

Seems like this has happened in the last two months.

**Comment by jrudess** [comment]
Are you using streamlink or ffmpeg to record and did it get upgraded recently?  Does the file-size check detect that the recording size isn't getting larger and stop and restart the recording?

**Comment by forsomefun2** [comment]
recording appears to be stuck (counter=1), file size is not increasing: 425MB

**Comment by jrudess** [comment]
Old plugin that is no longer supported, closing this issue.
