### ISSUE TITLE
MFC blocking recordings

### ISSUE THREAD

**Issue by zoopzorp** [jrudess/streamdvr#144]
Anyone else have their MFC recordings only record "Unusual activity has been detected from your IP address"? I tried lowering the update rate, but it didn't seem to help. I wonder if they're detecting something a genuine client sends that these scripts are now not.

**Comment by PurrSevere** [comment]
Yeah this started yesterday for me. Seems like they're catching on now.

**Comment by zoopzorp** [comment]
I've noticed one of the larger cap databases had their recordings affected by it too, but they seem to have found a fix.

I'm going to do some experimenting to see what I can come up with. I'm able to use streamlink to load streams fine locally, so either it's only something that triggers after a certain period of time or it's not something required to be sent when the video is loaded.

I wonder if we'd get away with having different IPs for scanning model status and recording.

**Comment by subjectnorica** [comment]
Same for me as well. Seems like it kicked in over the weekend.

I did some tests of my own to see what triggered the "Unusual activity" and in my case, it was only triggered by requests to their older API for accessing m3u8 streams. It only took a short time on a fresh IP. The widescreen streams seemed to work fine even after the trigger.

It seems they're using a DASH protocol instead of m3u8 for their 4:3 streams so it makes sense that they're targeting the m3u8 requests. I attempted to convert my setup to use DASH in the past because of other issues, but the results were jumpy and some files had corrupted timestamps (which is a separate issue I've been trying to figure out). However, using DASH hasn't triggered the warning so far so perhaps that's something to look into.

RTMP seems to work as well, but I haven't used it much so I'm not familiar with how well it does quality-wise in the long run.

**Comment by zoopzorp** [comment]
Hmm, I tried swapping the URL to use the DASH manifest, but I'm still receiving the block. Did you have to wait for it to clear (does it ever clear?) or is there more to using DASH than just changing the playlist URL? You mentioned the older API so maybe we need to modify how MFCAuto fetches info about the model.

**Comment by Hampster82** [comment]
Yup, was just coming to make this post myself. Hopefully we can solve this.

**Comment by subjectnorica** [comment]
@zoopzorp I ended up resetting my IP address to clear the block, sorry I forgot to mention that. While the block is in place, DASH will also redirect to the warning stream. After switching to a new IP, simply swapping the URL to use the DASH manifest has worked since.

By older API, I simply meant the m3u8 playlists for 4:3 streams that they've basically deprecated. I haven't had any issues with MFCAuto triggering any blocks, but only time will tell.

I haven't had time to test the theory, but I have a suspicion that the block would trigger even if attempting to record an m3u8 stream without getting any model info. It seems like the most likely pattern they're checking for.

**Comment by zoopzorp** [comment]
Thanks for the extra info. Hopefully the block eventually drops off otherwise I'll need to get a new server (can't switch/add IPs)

**Comment by Hampster82** [comment]
@subjectnorica How would I go about switching to the DASH manifest?

**Comment by subjectnorica** [comment]
Wherever your URLs are being generated for streams that aren't in widescreen, just replace "playlist.m3u8" with "manifest.mpd". It is a different protocol than HLS so you may have to change the software you're using. FFmpeg seems to support DASH URLs out of the box, and Streamlink (past a certain version) includes the dash:// prefix.

**Comment by deiot** [comment]
> @subjectnorica How would I go about switching to the DASH manifest?

Also, the [old streamlink plugin](https://github.com/Damianonymous/streamlink-plugins/blob/master/myfreecams.py) has a convenient optional argument `--myfreecams-dash`, if someone interested.

**Comment by Hampster82** [comment]
Well, I thought I did it right and all since it was recording again, but got blocked again in about 5 minutes, so I guess not.
Suppose I will wait for someone smarter than me to update the script.

**Comment by deiot** [comment]
I just got blocked while recording a dash stream ;{

**Comment by subjectnorica** [comment]
I guess they caught on to that as well :/

**Comment by forsomefun2** [comment]
Did you all get blocked?

HD models still work for now

**Comment by zoopzorp** [comment]
I wonder if it's something as simple as them checking the user agent. I believe streamlink just sends python's default. I'll need to spin up a server to have a clean IP to test with and see what happens with a proper user agent and DASH.

**Comment by deiot** [comment]
> I wonder if it's something as simple as them checking the user agent.

I just tired with a chrome browser user agent and got blocked within 5 minutes.

**Comment by Hampster82** [comment]
Could it be detecting MFCAuto in some way?

**Comment by deiot** [comment]
> Could it be detecting MFCAuto in some way?
I used ffmpeg and streamlink with manifest.mpd link and got blocked really fast, so I don't think so.

**Comment by vcl1** [comment]
Using ffmpeg m3u8 or mpd with or without passing the user agent and referer makes no difference still blocked 
`ffmpeg -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0" -referer "https://www.myfreecams.com/" -i "https://video702.myfreecams.com/NxServer/ngrp:mfc_119408970.f4v_desktop/manifest.mpd" -c copy test1.ts
`

But if I get a new ip and keep the cam open in a browser ffmpeg records without problem.
`ffmpeg -i https://video702.myfreecams.com/NxServer/ngrp:mfc_119408970.f4v_mobile/playlist.m3u8 -c copy test2.ts
`

**Comment by zoopzorp** [comment]
My best guess so far is that the website is now sending periodic pings or other authentication packets to the server. I'll need to sniff the traffic to see if I see anything interesting.

**Comment by subjectnorica** [comment]
It looks like they're using Wowza Streaming Engine for many streams, which documents a lot of security features. Some streams are being played over WebRTC and there are websocket connections that specifically mention "auth", but that's the only obvious authentication I could find.

@vcl1 I also had the site open and sort of clicked around a bit before running ffmpeg with similar settings (although I added the referrer in `-http-headers`) and it worked as long as I tried it.

@zoopzorp Monitoring the web traffic, it does seem that it makes a request to 'clear.gif' immediately before requesting the first 'manifest.mpd' for that session, but never for any streams loaded after that. I can't test it right now, but perhaps that's the ping?

**Comment by Hampster82** [comment]
Anyone figured out anything concrete?

**Comment by nerdydude** [comment]
They are definitely detected MFCAuto as an unauthorized client.

**Comment by Hampster82** [comment]
It's not MFCAuto, it's something with the way the recording happens with ffmpeg that triggers it.

**Comment by nerdydude** [comment]
There are multiple triggers. Yes there is a ffmpeg/streamlink trigger, but once you get past that one, you have the client triggers which is harder to get around.

**Comment by Hampster82** [comment]
On my end MFCAuto hasn't triggered anything at all.

**Comment by PurrSevere** [comment]
@Hampster82 What is your scan interval setting set to? I'm thinking it has something to do with that. I setup a separate server with a 1 hour scan interval and haven't had any problems. When I do get banned it's when I have it set to 5 minute scan intervals.

**Comment by gammagramma** [comment]
Anyone found a fix? I noticed that sometimes no trigger happens and the recording is normal, but more often than not that is not the case.

**Comment by wtnicolau** [comment]
Any solution?

**Comment by Hampster82** [comment]
I haven't seen one, and I wonder if someone found one would they be keen on sharing. I imagine MFC folks are reading various discussions about their blockers online, and if someone were to share a solution MFC might quickly adapt.

**Comment by zoopzorp** [comment]
I've yet to find a permanent solution. Everything I think works still eventually gets blocked.

What's interesting is that I've managed to trigger the block temporarily using their website, mainly when my connection dips and the video continues while the interface is not connected. This leads me to believe it's some sort of ping that is sent, or even just the presence of a client in the model's room while the stream is being used. I'm able to record streams successfully without issue if I have the same stream open in the browser.

Another thing to note is that one of the large cap sites (a hub, you might say) seems to be unable to find a workaround as well and they've got quite the technology stack powering that thing (if you read their about section). If they can't figure it out with financial incentive I'm not sure anyone will be able to.

If I get the time I may write my own mock client which only does the basics of idling in a chatroom and pair it with an external MFCAuto instance to get model status and see how that goes.

**Comment by nerdydude** [comment]
> I've yet to find a permanent solution. Everything I think works still eventually gets blocked.
> 
> What's interesting is that I've managed to trigger the block temporarily using their website, mainly when my connection dips and the video continues while the interface is not connected. This leads me to believe it's some sort of ping that is sent, or even just the presence of a client in the model's room while the stream is being used. I'm able to record streams successfully without issue if I have the same stream open in the browser.
> 
> Another thing to note is that one of the large cap sites (a hub, you might say) seems to be unable to find a workaround as well and they've got quite the technology stack powering that thing (if you read their about section). If they can't figure it out with financial incentive I'm not sure anyone will be able to.
> 
> If I get the time I may write my own mock client which only does the basics of idling in a chatroom and pair it with an external MFCAuto instance to get model status and see how that goes.

You do not have to create your own mock client. MFCAuto has the ability to "join" rooms and sit idle there. One of the first programs ZombieAlex made was a chat logger, which did just that. And I have noticed that it does extend my ability to record when I use the joinRoom function vs not joining.

**Comment by zoopzorp** [comment]
> You do not have to create your own mock client. MFCAuto has the ability to "join" rooms and sit idle there. One of the first programs ZombieAlex made was a chat logger, which did just that. And I have noticed that it does extend my ability to record when I use the joinRoom function vs not joining.

Interesting, thanks for the tip. I was thinking that MFCAuto joined the room already and some other part of it was triggering their block, but I will give it a go having it join the rooms. I'm going to still use a remote instance of MFCAuto to query the model status to see if that lets it work for longer.

**Comment by nerdydude** [comment]
> Interesting, thanks for the tip. I was thinking that MFCAuto joined the room already and some other part of it was triggering their block, but I will give it a go having it join the rooms. I'm going to still use a remote instance of MFCAuto to query the model status to see if that lets it work for longer.

Yea I have been using mfc-node and modifying that and MFCAuto. I am still running into issues, so I haven't solved it, but I have noticed that streamdvr gets killed in like 3-4 minutes while node can go for about an hour before I get blocked. 

It should be worth mentioning that the popup bubble on their site shows a stream, but doesn't join the room.

**Comment by wtnicolau** [comment]
I was able to start this stable stream

https://video549.myfreecams.com:8444/x-hls/11820277/113541146/7b0b75556a/WzEyMDI4OTg0OSwwLDEsMCwwLDAsMCw1MjIyNjM2XQ%3D%3D/mfc_a_113541146.m3u8?nc=0.8400031097533803

Any idea? to generate a new type of url???

**Comment by zoopzorp** [comment]
It seems MFC is offering streams over WebRTC for certain models now. I've had luck "resetting" a ban by successfully streaming a WebRTC stream for a bit. I've yet to find a way to connect to the WebRTC stream outside of the browser. As a temporary workaround, you can use the MediaStream recording API to record streams you have open in your browser.

**Comment by subjectnorica** [comment]
I've had really good luck recording streams (including the ones running over WebRTC) using a program called MFCdump that uses RTMP (because flash is still around). It seems to have issues connecting to what would be the HD HLS streams outside of flash, but I assume that the code hasn't been updated in a while.

The link where I found the binary said the program was "little modified" but the original source seems to be "gomfc". I'm hesitant to paste links, but the source is on github. I haven't tried compiling it to see if it works the same.

I'm curious to try recording with the MediaStream API. It sounds a bit tricky to manage the incoming data, but I'm sure it could work for shorter recordings. Good to know as a workaround.

**Comment by zoopzorp** [comment]
> I'm curious to try recording with the MediaStream API. It sounds a bit tricky to manage the incoming data, but I'm sure it could work for shorter recordings. Good to know as a workaround.

I was worried about storing an entire stream in memory so I have it dump the stream to a Blob and download it from the browser every 30 minutes. You then just need to concatenate the files together and you have the raw webm which can be converted with ffmpeg. It's not the best solution for automation, but for now it will do.

**Comment by nerdydude** [comment]
> It seems MFC is offering streams over WebRTC for certain models now. I've had luck "resetting" a ban by successfully streaming a WebRTC stream for a bit. I've yet to find a way to connect to the WebRTC stream outside of the browser. As a temporary workaround, you can use the MediaStream recording API to record streams you have open in your browser.

You need to connect to the websocket stream and it will provide the link info. If you check DevTools, you will notice a webrtc-session.json under the WS tab of networks. DevTools also lets you see the messages passed back and forth. 

My bans reset after a few hours. Do your bans not reset? 

*I have heavily modified my MFCAuto.

**Comment by zoopzorp** [comment]
> > It seems MFC is offering streams over WebRTC for certain models now. I've had luck "resetting" a ban by successfully streaming a WebRTC stream for a bit. I've yet to find a way to connect to the WebRTC stream outside of the browser. As a temporary workaround, you can use the MediaStream recording API to record streams you have open in your browser.
> 
> You need to connect to the websocket stream and it will provide the link info. If you check DevTools, you will notice a webrtc-session.json under the WS tab of networks. DevTools also lets you see the messages passed back and forth.
> 
> My bans reset after a few hours. Do your bans not reset?
> 
> *I have heavily modified my MFCAuto.

I've seen the bans reset almost instantly when opening a WebRTC stream, but haven't really tested that, just something I noticed while messing with it. I am able to get the WebRTC info from the websocket, but as far as I can see there's no libraries for any language that will connect to the stream.

**Comment by nerdydude** [comment]
> I've seen the bans reset almost instantly when opening a WebRTC stream, but haven't really tested that, just something I noticed while messing with it. I am able to get the WebRTC info from the websocket, but as far as I can see there's no libraries for any language that will connect to the stream.

Yea. I didn't notice any f4v recorders and gave up on the webrtc route. Plus I am trying not to deal with websockets. I was trying to mimic the mobile setup, but it connects to a websocket for every room you enter.

**Comment by wtnicolau** [comment]
any idea? page webcam player config?

<
div id = "video_wrapper"
style = "position: relative; height: 324px; width: 432px;" > < div class = "video_container videoplayerjs"
style = "position:absolute;top:1px;left:1px;"
id = "video25099551" > < div class = "video-js vjs-default-skin vjs-4-3 vjs-fluid vjs-big-play-centered vjs-p1 vjs-allow-controls fvideo_ff25099551-dimensions vjs-controls-disabled vjs-workinghover vjs-v7 vjs-playing vjs-has-started vjs-waiting vjs-live vjs-seeking vjs-user-inactive"
id = "fvideo_ff25099551"
tabindex = "-1"
lang = "pt-br"
role = "region"
aria - label = "Video Player"
style = "background-size: cover; background-image: url(&quot;https://snap.mfcimg.com/snapimg/773/320x240/mfc_125099551?no-cache=&quot;);" > < video id = "fvideo_ff25099551_html5_api"
class = "vjs-tech"
tabindex = "-1"
playsinline = "playsinline"
autoplay = ""
poster = ""
src = "blob:https://www.myfreecams.com/5546a9b9-7414-4bbf-bcf5-7a24ba53699f"
__idm_id__ = "169060353" > < /video><div class="vjs-logo-placeholder" aria-disabled="false"><div class="vjs-logo"><img class="vjs-logo-img" src="https:/ / img.mfcimg.com / files / images / svg / logo_speaker.svg "></div></div><script src="
https: //vjs.zencdn.net/vttjs/0.14.1/vtt.min.js"></script><div class="vjs-poster vjs-hidden" tabindex="-1" aria-disabled="false" style=""></div><div class="vjs-text-track-display" aria-live="off" aria-atomic="true"></div><div class="vjs-loading-spinner" dir="ltr"><span class="vjs-control-text">Video Player is loading.</span></div><button class="vjs-big-play-button" type="button" title="Play Video" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Play Video</span></button><div class="vjs-control-bar" dir="ltr"><div class="vjs-custom-control-spacer vjs-spacer ">&nbsp;</div><div class="vjs-volume-panel vjs-control vjs-volume-panel-horizontal"><button class="vjs-mute-control vjs-control vjs-button vjs-vol-2" type="button" title="Mute" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Mute</span></button><div class="vjs-volume-control vjs-control vjs-volume-horizontal"><div tabindex="0" class="vjs-volume-bar vjs-slider-bar vjs-slider vjs-slider-horizontal" role="slider" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" aria-label="Volume Level" aria-live="polite" aria-valuetext="50%"><div class="vjs-volume-level" style="width: 50%;"><span class="vjs-control-text"></span></div></div></div></div><div class="vjs-playback-rate vjs-menu-button vjs-menu-button-popup vjs-control vjs-button vjs-hidden"><button class="vjs-playback-rate vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" title="Playback Rate" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Playback Rate</span></button><div class="vjs-menu"><ul class="vjs-menu-content" role="menu"></ul></div><div class="vjs-playback-rate-value">1x</div></div><div class="vjs-menu-button vjs-menu-button-popup vjs-control vjs-button"><button class="vjs-icon-cog vjs-icon-placeholder vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite"></span></button><div class="vjs-menu"><ul class="vjs-menu-content" role="menu"><li class="vjs-menu-item vjs-selected" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="true"><span class="vjs-menu-item-text">Auto (600p - <small>2623kbps</small>)</span></li><li class="vjs-menu-item" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="false"><span class="vjs-menu-item-text">600p - <small>2623kbps</small></span></li></ul></div></div><button class="vjs-fullscreen-control vjs-control vjs-button" type="button" title="Fullscreen" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Fullscreen</span></button></div><div class="vjs-error-display vjs-modal-dialog vjs-hidden " tabindex="-1" aria-describedby="fvideo_ff25099551_component_249_description" aria-hidden="true" aria-label="Modal Window" role="dialog"><p class="vjs-modal-dialog-description vjs-control-text" id="fvideo_ff25099551_component_249_description">This is a modal window.</p><div class="vjs-modal-dialog-content" role="document"></div></div></div></div></div>

**Comment by wtnicolau** [comment]
record stable reference pop-up ?

GET /NxServer/ngrp:mfc_117990611.f4v_desktop/manifest.mpd?nc=0.6404687800560 HTTP/1.1
Host: video836.myfreecams.com
Connection: keep-alive
sec-ch-ua: Google Chrome 77
Sec-Fetch-Mode: cors
Origin: https://www.myfreecams.com
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
DNT: 1
Accept: */*
Sec-Fetch-Site: same-site
Referer: https://www.myfreecams.com/_html/player.html?broadcaster_id=17990611&target=new_window&username=SweetieM&vcc=1570335117
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Accept-Encoding: gzip, deflate

**Comment by e2489** [comment]
Did this ever get figured out, or is it still an issue? I haven't tried again since they IP banned me.

**Comment by jrudess** [comment]
Plugin is no longer supported, closing this issue.
