### ISSUE TITLE
[Feature Request] Support for sessionid/devicetoken for Pixiv login

### ISSUE THREAD

**Issue by henao941** [jrudess/streamdvr#145]
Could you add support for sessionid and devicetoken to be used instead of the username/password login process. There's been a bug in streamlink were you can't use username/password to login anymore to pixiv, but sessionid/devicetoken can still be used. 

This is the link to were the bug is discussed, https://github.com/streamlink/streamlink/issues/2515.

The command to set your sessionid/devicetoken are --pixiv-devicetoken and --pixiv-sessionid. I believe after that streamlink uses plugin-cache.json save your cache sessionid and devicetoken until it expires.

**Comment by YuuichiMizuoka** [comment]
I think those features where added with https://github.com/streamlink/streamlink/pull/2529 :)

as you said, its now possible to use --pixiv-sessionid and --pixiv-devicetoken to set the session id and device token

**Comment by jrudess** [comment]
Are you manually modifying m3u8_streamlink.sh to add the --pixiv-sessionid and --pixiv-devicetoken options to streamlink?  If so, I can add a field in pixiv.yml for user-defined recorder options and pass them to the record scripts.

**Comment by NanaKG** [comment]
I was going to create a request for the same thing. The --pixiv-sessionid and --pixiv-devicetoken options are in the most recent streamlink build by default, you dont have to modify files for it. I can use it to log in on a old streamlink file I have set up with python. I tried to copy the pixiv.py file and put it into the ubuntu version that I use for streamdvr but I still recieve the "error:No playable streams found on this URL"

**Comment by jrudess** [comment]
All site.yml files now allow passing custom arguments to youtube-dl or streamlink for both looking up m3u8/online-status as well as launching recordings.

For this use case, you can add the following to ~/.config/streamdvr/pixiv.yml to setup the sessionid and devicetoken for pixiv:

```
m3u8fetch_args:
  - "--pixiv-sessionid bleh"
  - "--pixiv-devicetoken bleh"
recorder: scripts/record_streamlink.sh
recorder_args:
  - "--pixiv-sessionid bleh"
  - "--pixiv-devicetoken bleh"
```
