### ISSUE TITLE
Streamer list search taking a long time to startup

### ISSUE THREAD

**Issue by t374** [jrudess/streamdvr#148]
Thanks for creating streamdvr, it's really been useful for me. I was wondering if their was a solution for my problem.

When streamdvr gets to the end of my streamer list it can take up to 1-6 minutes before it starts searching my list again, sometimes it can take up to more than 30 minutes, is there a way for streamdvr do immediately start searching again once it gets to the end of your list.

**Comment by jrudess** [comment]
Sorry for delayed reply.   How large is your streamer list?   Once all people in the list complete, then the code will wait for the amount of time specified in config.yml.   That amount of time should be a constant and not varying.

You may also want to turn on debug logging in config.yml which will give more details of what is going on, also with timestamps.
