### ISSUE TITLE
Setmax Listeners?

### ISSUE THREAD

**Issue by jfranco575** [jrudess/streamdvr#15]
Im sure this program wasnt made to have 1500 mfc id's added to the list so i got this warning. Is there anyway to increase the max people it can record or what is the current max it can handle?

`e(node:15344) MaxListenersExceededWarDiepounette  e EvAway       memory leak detected. 101 USERNAMELOOKUP listeners added. Use emitter.setMaxListeners() to`

**Comment by jrudess** [comment]
You can edit line 3 in streamdvr.js

`require("events").EventEmitter.prototype._maxListeners = 100;`
