### ISSUE TITLE
Picarto is not functional

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#156]
youtube-dl and ytp-dl give the error `'NoneType' object has no attribute 'get'`

Latest streamlink is correctly working for detecting online/offline, but the m3u8 returned is not working.

**Comment by DearFox** [comment]
Is Picarto still not working?

**Comment by DearFox** [comment]
I've already recorded a lot of streams with Picarto, so it seems to be working.

**Comment by jrudess** [comment]
Thanks for the update.  Tried it out again and confirmed that the ytp-dl issues appear to be functioning for both yt-dlp and streamlink.
