### ISSUE TITLE
Feature request: How to provide custom m3u8 URL file

### ISSUE THREAD

**Issue by inglesuniversal** [jrudess/streamdvr#159]
Allow to set up from / to times, daily run, etc

Regards

**Comment by jrudess** [comment]
I know this is a real old sighting, but I'm finding myself with some time on my hand and thought I'd do some coding.

The features don't seem too complicated to add, but I'd like to understand the use-case better.  Is the goal to prevent streamdvr from pinging the website to see if the streamer is active?   Or is the goal more about a specific streamer running certain types of content on certain days that you don't want to record (e.g. regular reruns, or uninteresting content on specific days)?

Can you elaborate on the "etc"? :-)

**Comment by inglesuniversal** [comment]
If I remember correctly, I would sometimes lose connection to certain stream, and needed a way to re-start the process if it failed.

Another use case is if I wanted to have the capability of storing a streams with a predefine schedule like a news cast or show
