### ISSUE TITLE
"[ERROR] TypeError: this.queryUser is not a function" when adding a MFC Model

### ISSUE THREAD

**Issue by SearchAndDestroy** [jrudess/streamdvr#16]
I am getting`[ERROR] TypeError: this.queryUser is not a function` when I try to add a MFC Model via the mfc_updates.yml file
I just updated to Node,js version 9.7.1 and I am on Win10

**Comment by jrudess** [comment]
Looks like I fixed this right as you filed it and I missed the sighting.  Should all be correct now if you pull again.

**Comment by SearchAndDestroy** [comment]
Thanks :) I'll pull later but I am sure it resolves the issue, so I'll close it.
