### ISSUE TITLE
Problem with new(?) MFC widescreen streams

### ISSUE THREAD

**Issue by Hampster82** [jrudess/streamdvr#18]
It seems that MFC has finally added widescreen streaming, noticed that one model was using it earlier today.

Recording doesn't seem to work though.
Log was just spamming 'started recording' 'can't find the file in folder' at every loop.

ID 10692328, if you need to test. She's not currently online though.

**Comment by ZombieAlex** [comment]
@jrudess You're going to want to look at MFCAuto v5.2.0, just published a moment ago.

**Comment by jrudess** [comment]
Thanks for the info, updated MFCAuto rev and switched to new Hls routine.

**Comment by ZombieAlex** [comment]
Looked at your change. Maybe I'm missing something. Just to be clear, [this code](https://github.com/jrudess/streamdvr/blob/master/mfc.js#L130) will not work for these hd streams. They've drastically changed the Url format for these streams. You can use my new getHlsUrl function to get the correct Url.

For testing purposes, "Skitty" is one model online right now in hd

**Comment by jrudess** [comment]
Bah, that's what I get for not checking the staging area closely before committing!

**Comment by Hampster82** [comment]
That was fast, good job.
