### ISSUE TITLE
Cannot read property 'nm' undefined

### ISSUE THREAD

**Issue by Rickadoo3** [jrudess/streamdvr#19]
Using the latest version and receiving this error.

I have tried updating node (was running 9.4.0) and running with fresh StreamDVR from latest build.
[Error.txt](https://github.com/jrudess/streamdvr/files/1849020/Error.txt)

I admit I might have missed something, but I really can't see anything.

**Comment by Hampster82** [comment]
I think you need to update MFCAuto for the latest version to work right. Run npm install again, that should do it.

**Comment by Rickadoo3** [comment]
Ignore the above, I sorted it.

Had to completely uninstall node and re-install from scratch, then copy streamdvr back in and run npm install. 

Now working, will continue to test over the next few days in case of issues.
