### ISSUE TITLE
CB Updates not persisting

### ISSUE THREAD

**Issue by snickity** [jrudess/streamdvr#2]
When removing a model using cb_updates.yml the change is reflected in the console but is not saved to cb.yml so the model starts recording again if the app is restarted.

**Comment by jrudess** [comment]
I wasn't able to replicate this in the development branch, so I've merged all my latest fixes to master and made a release.  Please try again with v0.7.3 and if you can still reproduce it, reopen the issue

Note:  launch the new version as 'node streamdvr.js'
