### ISSUE TITLE
Not picking up when models come back online

### ISSUE THREAD

**Issue by Rickadoo3** [jrudess/streamdvr#21]
Hey, 
When all the models in the mfc.yml list go offline and later any of them come back online, streamDVR fails to pick the stream up.

If even 1 of the models stays online then it continues to work perfectly.

So, in theory, if I could find a stream that is online 24hrs 7days a week it would continue pick up when any of the other streams appear online.

I have attached the log, hopefully that helps.
[streamdvr.log](https://github.com/jrudess/streamdvr/files/1858107/streamdvr.log)

Thanks for the great work so far though dude, keep it up :D

**Comment by PurrSevere** [comment]
Can confirm this issue. Happens at least once or twice a day for me.

**Comment by jrudess** [comment]
This one has me puzzled.  I have not been able to reproduce it on my end at all in the last week or so.  Will investigate adding better debugging messages to help track this down and will link the commit here when they're ready.

**Comment by Rickadoo3** [comment]
I have a feeling this is a network issue either with the ISP or possibly even a hop point between my ISP and MFC. I say this because MFC keeps bombing back to the "connecting to database" screen randomly when viewing from the lounge and because the last week or so StreamDVR has not been following this behaviour quite so much. Still misses occasionally, but no where near as often.

I tend to (if I have time and access to my phone) remote desktop into the PC and restart node mid-afternoon, it's usually fine then until the early hours of the morning so I restart it again before I go to work.

**Comment by jrudess** [comment]
I've had at least a couple cases of soft-lockup where no one is listed as streaming, but if I kill the script and restart, mfcauto immediately picks up a few people online.   so I think mfcauto is getting hung up somehow.  

I mostly started noticing these pbolems after I made two changes/fixes related to how I use MFCAuto.  First, properly enabling websocket connections to MFC, and second was some extra checks to prevent trying to capture models not really online (by getting the proper 'bestsession' handle from mfcauto).

Both of these could be related to the kind of symptoms I see.   Websockets can be reverted with `mfcWebSockets: false` in mfc.yml, but I'll need to make some small edits so I can flip back and forth on the 'bestsession' changes to see if I can track anything down there.

**Comment by Rickadoo3** [comment]
that would make sense, I have tried with mfcWebSockets: false and mfcWebSockets: true. With it set to "true" I had slightly ( very little difference really though) less hangs. 

Seems to have been more reliable lately though, even though I haven't changed anything or updated streamDVR.
