### ISSUE TITLE
New idea ...

### ISSUE THREAD

**Issue by sms-mitschs** [jrudess/streamdvr#25]
Is there a way to run this application on a headless server (ubuntu 16.04)? If yes, then give me a hint on how to do that, if not then this might be a great addition for a great piece of software.

This is needed because I cant keep open a ssh session all the time.

Thanks again for a great piece of software

**Comment by kuchenstrudel** [comment]
Connect with SSH, start `screen` or `tmux` and then it will continue to run even if you quit your SSH session.
`screen -r` or `tmux a` to reattach your session when you reconnect. `man screen` or `man tmux` for more information (like manual detaching and so on).

**Comment by jrudess** [comment]
Yup, I run it directly on a NAS (freebsd based) in a tmux session.
