### ISSUE TITLE
Recording not marked as finished

### ISSUE THREAD

**Issue by SearchAndDestroy** [jrudess/streamdvr#3]
Hi,
When a streamer stops streming (CB or MFC, not tested on Twitch) the recording itself is correctly stopped and the file moved but the scripts still sees it as recording and tried to end ffmpeg. The ffmpeg process is correctly closed and is no longer running, it's not seen as terminated by the script.
The machine is running Win10 and node 8.6.0
I cloned  to a new machine with node 9.2.0 running Win10 and it has the same problem.

**Comment by jrudess** [comment]
I haven't yet been able to reproduce with the dev branch, and I believe I remember running into this.  I pushed out a new release version.  Can you double check if you can still reproduce this with v0.7.4?

**Comment by SearchAndDestroy** [comment]
Just update :) I'll edit to let you know if it's fixed.

**Comment by jrudess** [comment]
Thanks for the update.  Can you post your config.yml?

**Comment by SearchAndDestroy** [comment]
Sure :) I tried the 0.7.2 sources and that version is working with my config.
I renamed it to config.txt so it can be uploaded
[config.txt](https://github.com/jrudess/streamdvr/files/1620170/config.txt)

**Comment by jrudess** [comment]
Thanks, I was able to reproduce the issues using your settings.

**Comment by jrudess** [comment]
Fixed in v0.7.5
