### ISSUE TITLE
[request] streamlink suport bongacams.com

### ISSUE THREAD

**Issue by wtnicolau** [jrudess/streamdvr#30]
streamlink get url m3u8 bongacams.com

please update suport for bongacams.com

**Comment by wtnicolau** [comment]
Supported sites add bongacams.com streamlink =)

**Comment by wtnicolau** [comment]
my grade idea

https://s18.postimg.cc/4yvvfmcrt/idea.png

thanks for your attention!!!

**Comment by wtnicolau** [comment]
do a test yourself, i get url m3u8 from bongacams

https://pwn.sh/tools/getstream.html

insert url bongacams (the camera should be online) example (maybe offline for you) 

https://pt.bongacams.com/lovedjuice

and click (Get stream URL) and Copy URL m3u8 and

example url get https://ded6443-edge12.bcrncdn.com/hls/stream_lovedjuice/chunks.m3u8

set url m3u8 for rec any recoder DVR software

http://applian.com/replay-media-catcher/

print software for recoder m3u8

https://s18.postimg.cc/qmktqf84p/replymedia.png

What do you think of putting it in the automatic for people? you do not need a cam example chat open status, the person you are recording should manually verify this on the website!!!

((((( Thank you for your attention, without further words.!!!  ))))

**Comment by jrudess** [comment]
I will look into bongacams once I have worked out the kinks with streamlink for the existing sites.  I can't promise any timeline, but I don't see any information missing that I would need.

**Comment by Asynchr0nous** [comment]
streamlink itself directly supports bongacams but for few months its been having an issue where it  fails to detect certain models even when online. i did notice that when this happens and you open up models page in a browser, it will detect. To me i feel like its detect a script has been running for quite sometimes and blocks it or something.

**Comment by jrudess** [comment]
Support added in master branch, but not in a release version yet.  If you run into any problems please open a new issue.  Requires streamlink for URL fetching only, but either ffmpeg or streamlink can be used to record.
