### ISSUE TITLE
Continue Install Issue

### ISSUE THREAD

**Issue by longsack** [jrudess/streamdvr#31]
Run npm install
Stuck here, did as instructed in issue 26:
# npm install
The authenticity of host 'github.com (REMOVED)' can't be established.loadIdealTree
RSA key fingerprint is REMOVED.
[ .................] \ loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree

The install will not move forward at this point... just stops.  I removed the IP Address and RSA.

**Comment by longsack** [comment]
Was able to install... had to remove from lock file also.

**Comment by jrudess** [comment]
I haven't decided how to handle this situation, so I'm just leaving the repo as-is at the moment.  So my apologies for all you new folks trying to use the software.
