### ISSUE TITLE
Question:  Is Name Change Possible?

### ISSUE THREAD

**Issue by longsack** [jrudess/streamdvr#32]
name currently saves as model_date.ts (mp4)

Is it possible to save like model_site_date.ts (mp4).  (examplemodel_chaturbate_date.mp4)

Also is is it possible to save in an open directory, not individual models directories?

Thanks

**Comment by jrudess** [comment]
Actually it is! In config.yml you can set the following to true:

`includeSiteInFile: false`

For the directories set the following to false:

`streamerSubdir: true`

Someday I'll actually document the config options that are available. :-)
