### ISSUE TITLE
live.fc2.com

### ISSUE THREAD

**Issue by longsack** [jrudess/streamdvr#33]
First,

Thanks for this program!  Great work!

I have been looking for a program that can do the same thing for the site fc2.com (live.fc2.com), however I can't find one, or someone that can/will build one.  Could you look at that site and see if you can support it.

I have been on freelancer and offered $$$$ to have something like this built for that site, however the programs either do not want to work on adult scripts or do not know how to or understand what I want... and I have had to cancel a number of times.

Thoughts?

Thanks!!!!!  great script!

**Comment by jrudess** [comment]
In general, I prefer to keep streamdvr limited to just the 'dvr' functionality without needing to know  the details of how a site is implemented.   So if a program like youtube-dl or streamlink has support for the site, that simplifies its integration into streamdvr.

However, support can still be added, but interested parties will need to do a bit of the work to figure the implementation out:

* Details on how to query the online status of a channel (if the site supports any JSON API queries, that is preferred).
* Details on how to fetch the m3u8 for the channel

**Comment by jrudess** [comment]
I have added initial support for fc2.com in master branch, however I don't yet have a mechanism to correlate fc2 'user ids' with 'user names'.   So for now filenames will have the userid.

E.g. https://live.fc2.com/75834000/

**Comment by jrudess** [comment]
Forgot to mention that to use fc2.com you need a streamlink plugin that is available at https://github.com/back-to/plugins/

**Comment by jrudess** [comment]
There are not currently any functional streamlink plugins for fc2, so this remains an open issue.

**Comment by jrudess** [comment]
Found and put a streamlink fc2.py plugin in the plugins/streamlink directory of this repo.   Top-of-tree now supports FC2, but user-id's are only the integers since that is what the site seems to use.
