### ISSUE TITLE
Reworking the TUI

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#34]
I still use streamdvr mostly in 'dashboard' mode, but the concept just really does not scale to N number of sites supported.   I've reworked the TUI on the development branch, and am looking for people to check it out and give feedback.  I think most people generally disable the list and leave only the log, so I've also added a config.yml  option to completely disable the TUI and all log output is written directly to STDOUT like it used to be.

For the TUI:
* Left pane for status of all channels/sites to be recorded
* Right pane for log
* Either pane can be disabled

**Comment by Asynchr0nous** [comment]
I've been wanting to ask for this request for quite some time now due to extremely high cpu usage with the tui version but didn't want to sound ungrateful so didn't want to bring it up again so thank you for this. I will download it and give it a go.

**Comment by jrudess** [comment]
CPU usage feedback is something I'm interested in as well.  I made a lot of other fundamental structural changes in order to support adding the TUI, but I am expecting cpu usage to decrease with `tui: false`.

**Comment by Asynchr0nous** [comment]
after testing it for just 24hours, i can happily say that with the tui disabled the cpu usage has been decreased to what it should be (and was prior to the tui feature).

**Comment by jrudess** [comment]
ctrl-c always waits for any outstanding ffmpeg/streamlink processes to quit.  So the first time it is pressed, I pass it down to the ffmpeg or streamlink processes, and if they don't quit then streamdvr won't exit.

This happens occasionally  for me with ffmpeg, and a lot for for streamlink.  Usually they will end if you pass them a 2nd ctrl-c, but I've seen streamlink require 3 or 4.

I did some quick testing with nothing recording and it looked like it was always exiting correctly.

**Comment by Asynchr0nous** [comment]
i can confirm that the problem mentioned here https://github.com/jrudess/streamdvr/issues/22 still exists.
i  just came back to check the script to only find out that it has been stuck for the last 27mins (at time of posting). i really don't know what causes this. it is still an improvement from version 0.7.7 onwards since with those the issues occured much earlier (after starting the scripting).

**Comment by Asynchr0nous** [comment]
> Stuff will only print if a model changes state, so it is normal to see hours go by with no printouts.

Ah right thanks, I was not aware of this of this change since i'm used to it printing stuff would every x seconds. I'll keep an eye on it to analyse its behaviour over the next few days.

**Comment by jrudess** [comment]
TUI disabling changes are now merged back to master branch
