### ISSUE TITLE
Keep logging to streamdvr.log with TUI set to false

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#36]
This would be a feature I'd like to see implemented as it'll work better for my current setup.

**Comment by jrudess** [comment]
I was debating about that when I shut it back off by default.   Before I had the TUI I used the following to create my logs:

`node streamdvr.js | tee streamdvr.log`

The above will overwrite the log if it exists, or you can have it append with:

`node streamdvr.js | tee -a streamdvr.log`

Of course, that may not be as easy to accomplish on one particular OS :-)

With the TUI, the above didn't work so I redirected to a log as well.  I'm not opposed to adding a couple new config options to control how logging behaves though if tee is not available.

**Comment by jrudess** [comment]
New config options will be:

`logenable: true`
`logappend: true`

**Comment by jrudess** [comment]
Added with 3341590118128aa3f14e31d4e8a94d87c5d4b91f

**Comment by PurrSevere** [comment]
Thank you!
