### ISSUE TITLE
Help for code-illiterate?

### ISSUE THREAD

**Issue by mcdude910** [jrudess/streamdvr#41]
I have a feeling this is not the place to do this but I can't seem to find another way to find help from jrudess as they haven't made their email address public and it appears I'm the only one interested in this project that has this issue.  I'm very sorry if this is inappropriate for this section and/or this website, but I wanted to make known that this project obviously has a lot of appeal for those less inclined with coding and programming.

I would like to make use of this project for DVRing streams of a specific model on MFC, but however hard I try to follow the install-instructions, I can't seem to figure out what I'm doing.  I've installed all dependencies but then I'm stuck from there.  I would very much appreciate, however unlikely I am to get it, a detailed tutorial for using this project, including basic instructions for using npm in this exact scenario.  I think a detailed step-by-step tutorial would be good for the readme file as, like I said, this project could see a lot of traffic if it was easier to understand.

I know how this sounds, I really do.  If this isn't the place for such a query, I understand that this will have to be pruned.  If necessary (and you would like to help me learn this better), my email is mcdude910@gmail.com.  I appreciate you reading this at the very least.

**Comment by Ptibouc77** [comment]
Hi if you need some information/help to make this works, you can go on vola: https://volafile.org/r/nJioNv (i will delete this link later).
I motsly think your are missing MFCauto (got removed due to DMCA) without MFCauto MFC will not work.

**Comment by jrudess** [comment]
Unfortunately, MFC won't work out-of-the box at the moment.   

The good news -- I'm looking into an alternative, as I've found a streamlink plugin for mfc, so I can allow the choice between mfcauto or streamlink as the MFC connection manager.

The bad news -- it'll still be a lot of manual setup work since you'll need the latest version of streamlink and a plugin that doesn't come with streamlink.  ;-)

Will update this with some more info once I have something working locally, but I don't have an ETA.

**Comment by mcdude910** [comment]
Well, while that would certainly be an issue, my issue is more in the setup.  Where it says "run npm install to fetch all of the package dependences listed in package.json." I'm lost.  I tried opening node and entering "npm install streamdvr" as well as dragging both the streamdvr JS file and the package.json file into the node application to seemingly no effect.  What am I missing?  I've installed node v10.5.0 (which included npm to my knowledge), the github bash and ffmpeg.  Keep in mind I have never used any of these apps and have no idea how to.  I'm not expecting a coding lecture from poor souls on github, but just a step-by-step instruction for installing streamdvr.  I understand MFC is not an option at the moment, but in that case, I would at least like to test it on my machine with Twitch or something in the meantime.  I appreciate the help folks.

**Comment by SearchAndDestroy** [comment]
Hi,
I am using Chocolatey to install all the depedencies since it's super easy to update them.
You can get it at https://chocolatey.org

Here is how I installed streamdvr:

1) Install Chocolatey: (https://chocolatey.org/install)
 ```
 Via an admin command prompt: @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
 ```
2) Install all the depedencies:
 ```
 cinst git
 cinst nodejs
 cinst ffmpeg
 cinst streamlink
 cinst youtube-dl
 ```
 To update to the latest version just run choco upgrade all

3) Install StreamDVR and the hlssession plugin:
 ```
 git clone https://github.com/jrudess/streamdvr.git
 git clone https://github.com/back-to/plugins.git
 md %appdata\streamlink\plugins
 copy plugins\plugins %appdata\streamlink\plugins
 cd streamdvr
 npm install
 ```
 
4) Edit config.yml to enable streamlink and adapt other options if needed:
 ```streamlink: true```
 The plugin is giving me error for CB so you may have to use ffmpeg instead.
 
 You should now be able to run it:
 ```node streamdvr.js```
 
 Add/Remove streamver by editing *_update.yml files

I hope this will help you :)

**Comment by mcdude910** [comment]
Alright, I think I got all of that.  Thank you so much.  Couple question; are you sure it's the update.yml files to add streamers?  There were default streamer names in the regular yml files, such as twitch.yml and cb.yml, but the twitch_updates.yml and cb_updates.yml just had `include [ ] exclude  [ ]` 
Also, am I supposed to just not be able to do anything with my command prompt after streamdvr is running?  The readme seems to imply some "TUI navigation" but nothing I type in cmd does anything once it's running.  How do I focus the streamer list or scroll active focus?  I also see instructions for TUI console commands.

**Comment by SearchAndDestroy** [comment]
yes you add/remove streamers via the *_update.yml files while the script is running and it updates every "scanInterval" seconds. Add the name between the [] e.g. include [streamer001,streamer002]
Yes you must disable MFC for now to run it.

**Comment by mcdude910** [comment]
Okay, thank you again.  This is super helpful.  So I don't have to do anything with twitch.yml or cb.yml, I added the streamers to the update files and saved them all while streamdvr was running.  Is there anything I have to do or should I just leave the cmd open in the background at all times and it'll record and save all streams?  Also, where do the streams save?

**Comment by mcdude910** [comment]
To my last post, I found the captured folder, but one of the CB streams I thought I was recording ended and now the captured folder is still empty.  Perhaps a fluke or because I started running streamdvr AFTER the stream had began; I don't know if that matters, but just to test this, I put Ninja in my twitch_update.yml.  I don't watch his stuff but he streams often enough that I should have results before long.

**Comment by mcdude910** [comment]
I found a someone on twitch streaming and added them to the update_twitch.yml and received this error in cmd 
`[20180703_091104] TWITCH   dakotaz added to capture list
[20180703_091109] TWITCH   dakotaz is streaming.
[20180703_091112] TWITCH   dakotaz recording started (dakotaz_20180703_091109.ts)
[20180703_091115] TWITCH   [ERROR] dakotaz, dakotaz_20180703_091109.ts not found in capturing directory, cannot convert to mp4`

**Comment by SearchAndDestroy** [comment]
It's working for me, except MFC and CB. Did you copy the plugins to your streamlink plugins folder?
Also did you enable streamlink? ```streamlink: true```
Also I don't convert the files since I am using Light Alloy to watch them and it can read *.ts file perfectly.
```[20180703-153908] TWITCH   1 streamer(s) in config
[20180703-153908] MIXER    2 streamer(s) in config
[20180703-153908] BONGA    1 streamer(s) in config
[20180703-153908] CAMSODA  1 streamer(s) in config
[20180703-153908] FC2      0 streamer(s) in config
[20180703-153911] TWITCH   twitchpresents is streaming.
[20180703-153919] TWITCH   [DEBUG] 1 streamer(s) to capture
[20180703-153922] TWITCH   twitchpresents recording started (twitchpresents_twitch_20180703-153919.ts)
[20180703-154002] TWITCH   [DEBUG] 1 streamer(s) to capture
[20180703-154002] TWITCH   [DEBUG] twitchpresents is already capturing

**Comment by mcdude910** [comment]
> Did you copy the plugins to your streamlink plugins folder?
If that was this from earlier: 
`md %appdata\streamlink\plugins
copy plugins\plugins %appdata\streamlink\plugins`
then yes.  I just did it again to be sure and overwrote everything.

> Also did you enable streamlink?
Yes, it says true.

I didn't make a conscious decision to convert the files to .mp4.  That was set to default.  If that's my problem, then I'll install Light Alloy, but I don't know how to make it NOT do that, or if that's even my issue.

**Comment by SearchAndDestroy** [comment]
Switch debug and debugrecodrer to true to get more info.
My config is as follow if you want to try:
```
captureDirectory: capturing
completeDirectory: captured
tui: false
streamerSubdir: false
scanInterval: 30
autoConvertType: ts
keepTsFile: true
streamlink: true
minByteSize: 0
maxByteSize: 0
dateFormat: YYYYMMDD-HHmmss
debug: true
debugrecorder: true
logenable: true
logappend: true
logshown: true
listshown: true
namecolor: magenta
statecolor: yellow
offlinecolor: blue
filecolor: green
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: true
includeSiteInDir: true
enableMFC: false
enableCB: false
enableTwitch: true
enableMixer: true
enableBonga: true
enableCamsoda: true
enableFC2: true

**Comment by mcdude910** [comment]
I copied your config and still got the same shit.  I must have missed something in the install but I followed it step-by-step.
![ss 2018-07-03 at 10 06 18](https://user-images.githubusercontent.com/40776153/42224738-ca8a39c4-7ea8-11e8-8461-72b1ddcf1fb6.png)

**Comment by mcdude910** [comment]
Okay, actually I got a whole new error here.
![ss 2018-07-03 at 10 10 24](https://user-images.githubusercontent.com/40776153/42224938-4f456594-7ea9-11e8-9f13-759e654db2e0.png)

**Comment by SearchAndDestroy** [comment]
The 2 files fc2.yml and fc2_updates.yml are missing. Disable FC2But you should get a log when the recording is starting.
fc2.yml is just ```streamers: []``` and fc2_updates.yml is the same as *_updates.yml

**Comment by mcdude910** [comment]
> The 2 files fc2.yml and fc2_updates.yml are missing. Disable FC2But you should get a log when the recording is starting.
fc2.yml is just streamers: [] and fc2_updates.yml is the same as *_updates.yml

Okay, I did all that and reset fc2 to true and that all works fine, but it didn't do anything for my main issue.
> What version of streamlink do you have? I think the plugin needs > 0.14
0.14.2
I updated everything with Chocolatey so it should all be up to date.

**Comment by mcdude910** [comment]
This is where I currently stand.
![ss 2018-07-03 at 10 30 07](https://user-images.githubusercontent.com/40776153/42226093-12a8175a-7eac-11e8-9887-093b795e179c.png)

**Comment by SearchAndDestroy** [comment]
Do you have streamlink, ffmpeg, etc in the current folder? If sop delete them (or move them) so those installed by Chocolatey are picked up.
Try streamlink --version to check

**Comment by mcdude910** [comment]
![ss 2018-07-03 at 11 40 56](https://user-images.githubusercontent.com/40776153/42230032-f86a4ab6-7eb5-11e8-9646-520ef3066551.png)
Nope, ffmpeg is in ```C:ProgramData\chocolatey\bin``` and streamlink is in ```C:Program Files (x86)\Streamlink\bin```

**Comment by SearchAndDestroy** [comment]
I see you are under C:\Windows\System32 which is a system folder. Can you try to move the streamdvr and plugins elsewhere, like C:\Videos\streamdvr or something like that?

**Comment by mcdude910** [comment]
So during the install process, I only had to be in admin cmd for installing chocolatey?

**Comment by SearchAndDestroy** [comment]
I don't think you need admin to run the script

**Comment by mcdude910** [comment]
![ss 2018-07-03 at 11 56 21](https://user-images.githubusercontent.com/40776153/42230913-1e24dbb6-7eb8-11e8-9f7b-8de0c5294a6a.png)
Still same error, damn.

**Comment by SearchAndDestroy** [comment]
I have no idea why it's not working :( You have the correct version.
Can you also recheck the streamer log to see if you are indeed getting the "unrecognized arguments" error?
And run streamlink --plugins from where the script is and verify that hlssession is listed?

**Comment by mcdude910** [comment]
Is it a problem that I have two streamlink folders?  One in %appdata that only contains the plugin folder and one in program files with everything else?

**Comment by SearchAndDestroy** [comment]
These plugins should be in %appdata%\streamlink\plugins i.e.. C:\users\mcdud\AppData\Roaming\streamlink\plugins
No one is the program itself and the other for the plugins.

**Comment by mcdude910** [comment]
ohhhh that's it.  Not to call you out, but when you gave the step-by-step, you had my paste
```md %appdata\streamlink\plugins
copy plugins\plugins %appdata\streamlink\plugins```

without a percent-sign after appdata, so I think it created a new folder instead of using my regular AppData folder.  I've moved it now and everything appears to be working perfectly.

**Comment by SearchAndDestroy** [comment]
oops, you are right :) Sorry about that. I edited the message to correct it.

**Comment by mcdude910** [comment]
I should have known better; I've been to %appdata% plenty of times.  I guess I just figured cmd must have known what I meant and maybe the second percent-sign would have made some error.  Thank you so much for all your help, seriously.

Now we just need to get MFC working again and I'll be all set.  Just to be clear, even with MFCauto, there's nothing I can do about getting that working, correct?

**Comment by mcdude910** [comment]
and lastly, is there a way to stop a recording aside from closing cmd entirely or excluding a streamer from the *_updates.yml.  When I did either of those, the .ts file stayed in the capturing folder instead of moving to the captured folder.  I figure I did something wrong.

**Comment by SearchAndDestroy** [comment]
You need to have MFCAuto locally for MFC to work but streamlink has a plugin and we just need to wait for jrudess to implement it :)
I don't think there is a way to stop just one recording except excluding the streamer.
Glad it's finally working :)

**Comment by mcdude910** [comment]
Yeah, I got it working fine with Twitch and Camsoda, but I am having trouble with chaturbate, but I think someone said there were problems with that at the moment.

Would you have any idea how to implement MFCAuto to work because I have the zip of it.

**Comment by mcdude910** [comment]
Along with Chaturbate, Bongacams is another that isn't working for me still.  Not a big deal, I don't use either website, but thought I would bring them up.

**Comment by jrudess** [comment]
To exit cleanly press 'q' or 'ctrl+c'.  This will stop all existing recordings and post-process convert them to mp4 before ending.

Lots of bug fixes in master branch today and chaturbate should be working again.

**Comment by jrudess** [comment]
Support to use streamlink for MFC instead of mfcauto is in master branch now.   Use 'enableMFCSL' in config.yml, and config/mfcsl.yml to control it.

**Comment by jrudess** [comment]
Forgot to mention that mfcauto still has features that streamlink doesn't have, such as looking up the user-id to track name changes and continue recording.
