### ISSUE TITLE
Streamlink + CB feedback

### ISSUE THREAD

**Issue by Hampster82** [jrudess/streamdvr#44]
For one it seems slower to start recording. Starting separate instances of the old and new methods and the new seems to take exactly 30 seconds to list models as if on a delay, where the old takes 3 seconds or so. Not a big deal since it's only the initial start that takes that time, just something I noticed.

More critically, the new method doesn't seem to work for me at all.
It's just an endless loop of "10 streamers to capture, recording started, not found in capturing directory, cannot convert to mkv". I'm trying to use ffmpeg to record and looking at the task manager, it seems like the ffmpeg process never even starts.

This is with a completely fresh streamdvr, only thing I brought over from my old install was the streamer list.

Windows 10, nodejs 10.5.0, streamlink 0.14.2, also latest ffmpeg as of today.

**Comment by SearchAndDestroy** [comment]
I am also unable to record CB. It works perfectly for Twitch or Mixer.
```[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin hlssession for URL hlssession://https://edge23.stream.highwebmedia.com/live-hls/amlst:testmodel-sd-cb57d909759a51d879e571354198802e2045ccea3bba690c4649f284daf7a4b6_trns_h264/chunklist_w1192668953_b1896000.m3u8


[cli][debug] Plugin specific arguments:
[cli][debug]  --hlssession-segment=True (segment)
[cli][debug]  --hlssession-time=300 (time)
[plugin.hlssession][info] This is a custom plugin. For support visit https://github.com/back-to/plugins
[plugin.resolve][info] This is a custom plugin. For support visit https://github.com/back-to/plugins
[plugin.resolve][debug] User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
[plugin.resolve][info]   1. URL=https://edge23.stream.highwebmedia.com/live-hls/amlst:testmodel-sd-cb57d909759a51d879e571354198802e2045ccea3bba690c4649f284daf7a4b6_trns_h264/chunklist_w1192668953_b1896000.m3u8

error: Unable to open URL: https://edge23.stream.highwebmedia.com/live-hls/amlst:testmodel-sd-cb57d909759a51d879e571354198802e2045ccea3bba690c4649f284daf7a4b6_trns_h264/chunklist_w1192668953_b1896000.m3u8
 (Invalid return character or leading space in header: Referer)```

**Comment by jrudess** [comment]
I had this working at one point on CB, and think I know what I messed up.   It looks like I need to process the string that I get back from streamlink and filter out carriage returns.   I don't see that issue with streamlink for other sites.

**Comment by jrudess** [comment]
Initial startup times will definitely be slower for CB in the short term.  The script is currently executing streamlink to do model lookups in a parallel fashion.   Once the flow is clean, I'll re-integrate the parallel-batch code, in a more generic spot that will apply to all sites using streamlink (or youtubedl) to do online-status queries.  This is one of the big reasons I didn't create a release tag yet for these changes.

**Comment by Hampster82** [comment]
Alright, rad. Looking forward to it.

**Comment by SearchAndDestroy** [comment]
Yes just readd 
```
           url = url.toString();
           url = url.replace(/\r?\n|\r/g, "");
```
at line 96 of core/basicsite.js and CB is recording without problems.

**Comment by jrudess** [comment]
CB should be fixed with 57f6b8e0

**Comment by jrudess** [comment]
Startup performance should be much improved with 1ae187c7

**Comment by Hampster82** [comment]
Just had some time to test the updates and everything's working great and the startup speed is greatly improved as well, good job.

**Comment by jrudess** [comment]
Yeah, I'm not surprised to see increased cpu usage.   Right now the only built in way to counteract that is to lower the batchSize setting in each site's yml.  That should kick off less simultaneous instances of streamlink on each cycle, with the side effect of each cycle taking slightly longer to run all lookups.

On linux, you can launch node through nice to lower its priority.  The nice level should apply to all children processes launched from streamdvr.

`nice -n 19 node streamdvr.js`

But I don't believe that 'nice' works yet in WSL

**Comment by SearchAndDestroy** [comment]
It's working great, apart for the CPU usage spike but I can indeed reduce the batchSize.

**Comment by kuchenstrudel** [comment]
I wonder how this will affect a first gen Raspberry Pi.

**Comment by Hampster82** [comment]
I'm not seeing batch size affecting this at all. Lowered it from the default 5 to 1, only running CB script to test and it doesn't seem like it made any noticeable difference.

**Comment by jrudess** [comment]
I can see some inconsistent behavior with the number of simultaneous running streamlink instances vs what I'm expecting.  Definitely a bug here.

**Comment by jrudess** [comment]
Fixed with d2f64f24

**Comment by jrudess** [comment]
Another perf fix that reduces the number of times I execute streamlink per loop with 4bdbe42c

Note that this commit also moves all of the yml files to a subdirectory named config

**Comment by Hampster82** [comment]
Batchsize definitely works now and makes an immediate difference, the other one is harder to gauge.

**Comment by jrudess** [comment]
The 2nd perf fix is much smaller.  Previously, for online streamers, I was fetching the m3u8 URL twice.  But in a large record list, most streamers are not online, so proportionally the number of streamlink calls saved isn't that high.

**Comment by Hampster82** [comment]
Ah, that makes sense then.

I don't know anything about streamlink as such, so I take it it's not possible to fetch the list with a single instance, otherwise you would have done so already. Unfortunate.

**Comment by jrudess** [comment]
Closing this issue with release v0.10.0.  Feel free to file new issues if there are others things to fix/improve.
