### ISSUE TITLE
[Request] Add support for CAM4 (streamlink)

### ISSUE THREAD

**Issue by Ptibouc77** [jrudess/streamdvr#46]
As you can see https://streamlink.github.io/plugin_matrix.html Streamlink support cam4 it will be great to have this included in streamdvr.

**Comment by jrudess** [comment]
Done -- note that cam4 appears to use rtmp by default when specifying "best" to streamlink for quality.   I've left that as is since I haven't spent much time investigating cam4 streams yet.

If you prefer HLS streams, you can edit plugins/cam4.js as follows:

    -        super("CAM4", "_cam4", tui, "https://www.cam4.com/", true, "best");
    +        super("CAM4", "_cam4", tui, "https://www.cam4.com/", false, "480p");
