### ISSUE TITLE
MFC Chat?

### ISSUE THREAD

**Issue by mcdude910** [jrudess/streamdvr#47]
Is there any way to record the chat logs for particular models on MFC?

**Comment by jrudess** [comment]
Not with streamdvr.  It's not a functionality I'm interested in for this program, but it is fairly easy to implement using the mfcauto libraries if you can find copies of them (the official repo was removed from github).

**Comment by mcdude910** [comment]
I know this thread is closed but would you be able to possibly tell me how to do this?  I do have a copy of MFCAuto and have been able to use it with StreamDVR just fine, but I don't know how to use MFCAuto on its own as it doesn't seem to have an MFCAuto.js file or anything.

**Comment by jrudess** [comment]
There's a good code base for doing this with an example listed in the README here: https://github.com/ZombieAlex/MFCLogger
