### ISSUE TITLE
Missing Cam4 in Config.yml and tui.js

### ISSUE THREAD

**Issue by Ptibouc77** [jrudess/streamdvr#49]
To fix mssing Cam4 in config.yml we have to add this  : `enableCam4: true` or `enableCam4: false`.
Also to add the missing Cam4 in tui.js we need to add this : `(this.config.enableCam4     && siteName === "cam4") ||` behind `(this.config.enableCamsoda  && siteName === "camsoda") ||` and before `(this.config.enableFC2      && siteName === "fc2")) {`

**Comment by jrudess** [comment]
Fixed in 6e444ef34fdc987556fd0d70203a6019eca36dba
