### ISSUE TITLE
[mfcsl] streamlink returning m3u8 for wrong streamer

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#50]
Have observed some cases of the streamlink MFC plugin returning an m3u8 for a different streamer.  In debug.

Additionally, from log parsing, it appears that it is sometimes not returning a valid m3u8, triggering streamdvr to believe the streamer is offline and end the recording prematurely.

**Comment by Ptibouc77** [comment]
I edited the mfcsl.js to be able to use user id instead of Username (I have some model who like to change username every week) and i did not encounter any issue (except that the file is named with the user id instead but not a big problem)

**Comment by jrudess** [comment]
Could you post the diff?

**Comment by Ptibouc77** [comment]
Instead of: 
super("MFCSL", tui, "https://www.myfreecams.com/#", false, "best");

I use :
super("MFCSL", tui, "https://myfreecams.com/?id=", false, "best");

**Comment by jrudess** [comment]
Thanks! I didn't know about the ?id= url

**Comment by jrudess** [comment]
Streamlink plugin returning the wrong model's m3u8 appears to happen when the model is online but webcam is off.

**Comment by SearchAndDestroy** [comment]
It's sill starting to record the wrong model. I'll get model's logs later and check.
Would it be possible to use the Uid for the URL but provide a name for the filename in the config?
Like:
```
streamers:
  - uid: 12345678
    nm: ZeBestModel
```

**Comment by Ptibouc77** [comment]
Did you use user id like in my last message? I still use this method and this never happened to me.
I have CB MFCsl and Cam4 enabled.

**Comment by SearchAndDestroy** [comment]
@Ptibouc77 no I didn't because I prefer to have the name and not the uid and I am using another script for MFC but I could try.

**Comment by SearchAndDestroy** [comment]
The mfc plugin has been updated:
´´´
plugins.myfreecams: support for wzobs servers
plugins.myfreecams: DASH streams but only for h5video servers and --myfreecams-dash must be used.
´´´
I am now getting many attempts to start recording but it eventually starts. I am using the "?id=" version.

**Comment by jrudess** [comment]
support for mfcsl has been removed.
