### ISSUE TITLE
Latest update nothing is recording

### ISSUE THREAD

**Issue by slyfox99** [jrudess/streamdvr#51]
Unless I'm doing something wrong, nothing is recording now.
All models appear offline even though they are online on the site. 

Tested with CB and Camsoda.

**Comment by jrudess** [comment]
Please post your config.yml and versions of node, ffmpeg, and streamlink (if used).

**Comment by slyfox99** [comment]
I'm also using linux if that helps

node: v10.1.0
ffmpeg: 3.2.4-2~xenial
streamlink: I'm using the latest from the github linked posted in READ.me, but I didn't do anymore than what their READ.me said to do as far as setting up

config.yml

captureDirectory: capturing
completeDirectory: captured
tui: true
streamerSubdir: true
scanInterval: 300
autoConvertType: mp4
keepTsFile: false
streamlink: true
proxyenable: false
proxyserver: socks5://127.0.0.1:1080
minByteSize: 0
maxByteSize: 0
dateFormat: YYYYMMDD_HHmmss
debug: true
debugrecorder: false
logenable: true
logappend: true
logshown: true
listshown: true
namecolor: magenta
statecolor: yellow
offlinecolor: blue
filecolor: green
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: false
includeSiteInDir: false
enableMFC: false
enableMFCSL: false
enableCB: true
enableTwitch: false
enableMixer: false
enableBonga: false
enableCamsoda: true
enableFC2: false
enableCam4: false

**Comment by jrudess** [comment]
For streamlink recording, you also need the hlssession plugin from this repo: https://github.com/back-to/plugins/

Thats also where the myfreecams plugin for mfcsl is.  The way to install them it is to put the plugin.py files ~/.config/streamlink/plugins.

You can switch back to ffmpeg recording with streamlink: false

**Comment by slyfox99** [comment]
even when I turn streamlink to false streams still are not being picked up

**Comment by slyfox99** [comment]
Also I'm running off of master.

**Comment by jrudess** [comment]
I recommend setting debug: true and debugrecorder: true, and then looking for any modelname.log files to see if there are any errors from streamlink or ffmpeg.

**Comment by slyfox99** [comment]
User error.
I thought the streamlink github was the streamlink install. 
I didn't know I had to install it on the OS level. 
streams are recording again. 
sorry about that.

**Comment by jrudess** [comment]
No worries -- my readme is a little bit terse.
