### ISSUE TITLE
Streamlink recordings sometimes stop early

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#54]
I've only seen this happen once, but even with the hlssession plugion, streamlink recordings still appear to get stuck and stop recording, but without ending.

[20180711_231555] MFC      Name recording started (Name_20180711_231555.ts)
...
[20180712_003700] MFC      Name has logged off.
[20180712_003700] MFC      [DEBUG] Name is no longer broadcasting, ending streamlink capture process.
[20180712_004000] MFC      [DEBUG] Name is no longer broadcasting, ending streamlink capture process.
[20180712_004300] MFC      [DEBUG] Name is no longer broadcasting, ending streamlink capture process.
[20180712_004300] MFC      Name converting to Name_20180711_231555.mp4

Based on the log timestamps, the mp4 should be roughly 90 minutes long, but was only 16 minute long, and it took sending three separate SIGINT to streamlink to get it to end.   Unfortunately, debugrecorder was off.

**Comment by jrudess** [comment]
After more log investigation, it looks like every recording attempted last night had this problem and the longest mp4 captured was only 16 minutes.

**Comment by Asynchr0nous** [comment]
I run two scripts, one to limit video quality for which i use streamlink to fetch urls and other for general purposes. both use ffmpeg for recording but the streamlink one seems to stop alot more often. maybe the urls expires or some signals get sent to end the recording early

**Comment by nerdydude** [comment]
I think I found a solution to this problem. the mfc-node program had this feature of checking to see if the process is still running every few minutes. I retrofitted an older version( from before MFCAuto got pulled) to have this functionality. If you would like, I can upload it.

**Comment by kuchenstrudel** [comment]
> I think I found a solution to this problem. the mfc-node program had this feature of checking to see if the process is still running every few minutes. I retrofitted an older version( from before MFCAuto got pulled) to have this functionality. If you would like, I can upload it.

Sure, would be interesting to test.

**Comment by jrudess** [comment]
Unfortunately, streamdvr already checks if the process is running on each iteration.   But this has given me an idea to add a filesize check.  If the filesize does not change between "n" iterations (config.yml option) of the script, then we can assume the job is hung, and send sigint

The primary problem with this solution is streamlink tends to not honor sigint so it may still get permanently stuck.   Nevertheless, I think it is worth implementing.

**Comment by nerdydude** [comment]
> Unfortunately, streamdvr already checks if the process is running on each iteration. But this has given me an idea to add a filesize check. If the filesize does not change between "n" iterations (config.yml option) of the script, then we can assume the job is hung, and send sigint
> 
> The primary problem with this solution is streamlink tends to not honor sigint so it may still get permanently stuck. Nevertheless, I think it is worth implementing.

That is actually what mfc-node does.  My solution just checks on the process every 5 minutes(hard coded currently) to see if the file size has changed, if it hasn't, then it will kill the process. I am using ffmpeg for recording, so I cannot help with the streamlink problems. 

It doesn't require a new iteration, since i just added the call in the checkStreamerState method, so that if the isStreaming is true, then it will check on the process.

**Comment by jrudess** [comment]
I've committed the file size check on master branch.  If anyone sees any similar stuck issues, please open up an issue.  If no change is detected in 2 scanInterval, it will send SIGINT to the recording process, and continue doing that until the process ends (since streamlink sometimes takes 3+ SIGINT).
