### ISSUE TITLE
cam4 not recording - not found in capturing directory

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#56]
Soon as a model is online, it gives the above error. says recording started but doesn't actually record or anything. Also i noticed that the cam4 plugin is set to record only in 480p, which will fail to work most of the time since cam4 generally has single quality available that varies from model to model.

**Comment by jrudess** [comment]
Ah, it was a mistake that I checked it in that way.  I meant to leave it set to 'best', although 'best' isn't always 'best' since it picks the flash stream over the HLS stream often.

**Comment by Asynchr0nous** [comment]
is there a way in which we could select the best hls stream only?
