### ISSUE TITLE
Chaturbate error

### ISSUE THREAD

**Issue by mcdude910** [jrudess/streamdvr#57]
I keep receiving this error even though this model is definitely spelled correctly.  Not sure what could be going wrong.  The model isn't streaming right now while I'm getting this error and she hasn't since I added her to the program so I don't know if it will record or not, but something is definitely amiss if this error is appearing for no reason.

![ss 2018-07-17 at 04 53 56](https://user-images.githubusercontent.com/40776153/42844770-03e069ac-89e2-11e8-8984-0db0831a5fab.png)

**Comment by mcdude910** [comment]
Definitely no space there.
![ss 2018-07-17 at 11 59 39](https://user-images.githubusercontent.com/40776153/42858650-932f09fc-8a1d-11e8-97d5-1d596c78f830.png)

**Comment by jrudess** [comment]
Added to my list and will see if I can replicate with full debug logs.   I don't use CB a lot, but these kinds of errors are likely to not be related to streamdvr per say, as all connections to CB are being done by streamlink.  

But my best guess is that it's possible that CB still has some flash-only streams, and that the CB plugin may only support HLS.
