### ISSUE TITLE
[CB] error: Unable to open URL [...] Read timed out

### ISSUE THREAD

**Issue by kuchenstrudel** [jrudess/streamdvr#59]
I got this error yesterday (redacted):
> [$TIMESTAMP] CB [ERROR] $MODEL error: Unable to open URL: https://chaturbate.com/get_edge_hls_url_ajax/ (HTTPSConnectionPool(host='chaturbate.com', port=443): Read timed out. (read timeout=20.0))

**Comment by jrudess** [comment]
I believe this is an expected error to see during network connectivity issues or if CB servers are having problems.   As long as it doesn't crash streamdvr, then it's still useful to have in the logs to track times when you may be missing recordings.

**Comment by kuchenstrudel** [comment]
I didn't crash, correct. Closing.
