### ISSUE TITLE
request: Select "best" hls stream

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#60]
would it be possible to select the "best" HLS stream for plugins that also have live feed (which in most cases is worse) such as for cam4.

**Comment by Asynchr0nous** [comment]
found the solution here: https://streamlink.github.io/cli.html#cmdoption-default-stream
changing this line:

>  super("CAM4", tui, "https://www.cam4.com/", true, "best");

To something like this:

>  super("CAM4", tui, "https://www.cam4.com/", true, "480p,576p,600p,720p,768p,864p");


while it may not be the most efficient way of doing it, it gets rid of the problem of having to record a live feed (rtmp), which in my cases have alot of errors

**Comment by jrudess** [comment]
That seems like a reasonable solution

**Comment by Asynchr0nous** [comment]
Updated: just realised that this solution didnt actually select hls stream. The stream quality defined in "site.js" file also needs to be changed from "best" to whatever you want e.g. 720p..etc

**Comment by Asynchr0nous** [comment]
Update2:

So while the above method does work, sometimes you end up with stream qualities that are not defined which mean it ends up giving you errors. After searching for a bit I managed to find the perfect solution. 

In site.js under "core" folder, change this section:

> if (this.tui.config.streamlink) {
            params = [
                "-o",
                this.tui.config.captureDirectory + "/" + filename + ".ts",
                url,
                "best"

So that it includes an extra parameter:

> if (this.tui.config.streamlink) {
            params = [
                "-o",
                this.tui.config.captureDirectory + "/" + filename + ".ts",
                url,
                "best",
                "--stream-sorting-excludes=live"

**Comment by jrudess** [comment]
Sorry about delay on this one.  I've added the new switch you identified into the streamlink list of options.

The "best" argument being in any youtubedl based plugins is a mistake.
The "best" argument being in streamlink plugins is for the "model online" check only, but does not affect the actual recording arguments (as you discovered).

This definitely deserves a bit of cleanup so that there is much greater per-plugin control of everything.

**Comment by jrudess** [comment]
Looks like --stream-sorting-excludes=live causes problems for mfc because "best" is no longer an option only "best-unfiltered".   I've backed out the commit for now.

**Comment by Asynchr0nous** [comment]
tbh i didnt even know that got included into the code but it was only used for cam4 as it was an rtmp stream. also it reduced the problem of the video resolutuions changing multiple times mid stream. still happens but rarely. best results with exluding "live" and using ffmpeg to record (in case people want to manually enable it at some point)

**Comment by jrudess** [comment]
Ah, thanks for the extra info.  I need to have a better configuration option on per-site ffmpeg options, streamlink options, etc.   I'm looking at enabling fc2 right now and I see some rtmp stuff going on when streamlink launches it manually.

**Comment by Asynchr0nous** [comment]
I can't comment on how well the recordings are for this site but can you give me an example link so i can have a look. tried a random link manually from their site like `streamlink https://live.fc2.com/9494864/ best` but it didn't recognize the plugin

**Comment by jrudess** [comment]
I uploaded a plugin at plugins/streamlink/fc2.py in the repo.   I've enabled fc2 in master branch, as everything seems to be working.

**Comment by jrudess** [comment]
I've added --stream-sorting-excludes=live to the streamlink record options generated in ``basic.js```, but additionally, in ```scripts/record_streamlink.sh``` it is now best,best-unfiltered which I hope will avoid the case of undefined streams.

There isn't a functional cam4 plugin at the moment for testing, but I've confirmed that all existing sites are able to still record with this change using streamlink.

**Comment by johnthecracker** [comment]
@jrudess

Can you plese post complete link for this?

plugins/streamlink/fc2.py

or what tutorial or help file to read so I can figure out location of plugins/streamlink/fc2.py ?
I try hard to find that plugin or tutorial but just can't maybe because github is too complicated.
I am not the only one having trouble finding things here, other guys asked me to post a link to fc2.py,

https://github.com/streamlink/streamlink/issues/1892#issuecomment-443470237
