### ISSUE TITLE
Problem running latest version

### ISSUE THREAD

**Issue by Rickadoo3** [jrudess/streamdvr#61]
Trying the latest streamdvr, I keep getting 

"console.js:35
    throw new TypeError('Console expects a writable stream instance');"

Tried re-installing everything but can't get it to runl.

Have run npm install and all the modules are installed.

I think it's a nodejs problem and not a streamdvr problem, but I am hoping someone here has some idea what's going wrong.

**Comment by jrudess** [comment]
Make sure you have nodejs v10.1 or newer

**Comment by Rickadoo3** [comment]
I had updated node to the latest version which is why I never thought of checking the files. Looks like my Windows install decided not to let node overwrite existing files even though it asked and I told it to!

I have moved node to a non system drive, updated to the latest version. Had to npm install to get everything again and now it works........bloody windows UAC, it's total bullshit.

Thanks for the pointer though dude, all working now
