### ISSUE TITLE
Recordings missing?

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#62]
I'm currently using the latest version of the script to record ONLY bongacams and cam4 models and for some strange reason i've noticed that some of the recordings don't even exist after they get moved to "captured". Some models have been recording for hours straight yet i'm only finding either short clips or nothing at all. i also think that its failing to recording some models at all, meaning that it might say that "x model is already recording" but nothing might exist in the "capturing" directory.

Also I've had the auto conversion disabled on every version of the script so don't think the issue is there.

update: i think the issue is related to this https://github.com/jrudess/streamdvr/issues/54

**Comment by jrudess** [comment]
Can you let me know if you still see this with v0.11.0 for bongcams?

**Comment by jrudess** [comment]
bongacams removed.   Please open a new issue if you see this with v0.11.3 or newer
