### ISSUE TITLE
Auto Organize by site

### ISSUE THREAD

**Issue by forsomefun2** [jrudess/streamdvr#63]
The name Jrudess Seems familiar I feel like I've used your MFCRecorder at one point. 

Do you have any plans to allow auto organizing by site. I haven't had much time to play around with this program.  But it seems like for now it only does it by model. 

I think I need to use MFC instead of MFCSL because it will take to long to convert all the model numbers I have into their actual names. Where would I but MFCauto, I believe I possibly have it backed up somewhere.

**Comment by forsomefun2** [comment]
I do not think my MFCAuto will work it is python, and this version seems to be javascript. Maybe that is why it was not detecting it.

**Comment by PurrSevere** [comment]
I too wanted my recordings organized this way so I made a small edit to /core/site.js. You can see that here:
#8

**Comment by forsomefun2** [comment]
@PurrSevere 
Did you figure out where it is pulling the SIte name from? Is it possible to change that as well

**Comment by forsomefun2** [comment]
Thank you 
I found a copy of mfcauto but this one might work better
