### ISSUE TITLE
MFC plugin:  bug with adding new streamers from console command

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#68]
When using 'add mfc streamer' the log says that mfc.yml was updated, but nothing is changed.  

Temporary workaround is to run  the command a 2nd time which results in an error "streamer is already in the capture list" but then mfc.yml gets written with the new streamer.

**Comment by forsomefun2** [comment]
Are you talking about the document system with the .conf files?

Would it be possible to implement Beaston's Code for adding models? I think it just uses MFC auto to get the models ID?  But it allows you to just enter the name rather than have to find the ID.

`#!/usr/bin/env python3
import sys, configparser
from mfcauto import Client
import asyncio


Config = configparser.ConfigParser()
Config.read(sys.path[0] + "/config.conf")
wishlist = Config.get('paths', 'wishlist')

f = open(wishlist, 'r')
wanted = list(set(f.readlines()))


async def main(loop):
    if len(sys.argv) != 2:
        print('Must include a models name. ie: add.py AspenRae'.format(sys.argv[0]))
        sys.exit(1)

    modelName = sys.argv[1]

    print("Querying MFC for {}".format(modelName))
    client = Client(loop)
    await client.connect(False)
    msg = await client.query_user(modelName)
    client.disconnect()
    print()

    if msg == None:
        print("User not found. Please check your spelling and try again")
    else:
        if str(msg['uid'])+'\n' in wanted:
            print('{} is already in the wanted list. Models UID is {}'.format(modelName, str(msg['uid'])))
        else:
            f = open(wishlist, 'a')
            f.write(str(msg['uid'])+'\n')
            print("{} with UID {} has been added to the list".format(modelName, msg['uid']))
        print()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
    loop.close()
`

**Comment by forsomefun2** [comment]
Edit:
I got the old script I had for adding models from just the username to work again

Just need to make this into a python script
and run from python3

It also requires adding this to the config.yml
[paths]
wishlist =

Lastly just MFCAuto for python which goes into the 
/usr/lib/python3/dist-packages/  at least on ubuntu
which is here:https://drive.google.com/open?id=195bTjTCp4nWN-UwebrH1T_JFzBJC2E



```
#!/usr/bin/env python3
import sys, configparser
from mfcauto import Client
import asyncio


Config = configparser.ConfigParser()
Config.read(sys.path[0] + "/config.yml")
wishlist = Config.get('paths', 'wishlist')

f = open(wishlist, 'r')
wanted = list(set(f.readlines()))


async def main(loop):
    if len(sys.argv) != 2:
        print('Must include a models name. ie: add.py AspenRae'.format(sys.argv[0]))
        sys.exit(1)

    modelName = sys.argv[1]

    print("Querying MFC for {}".format(modelName))
    client = Client(loop)
    await client.connect(False)
    msg = await client.query_user(modelName)
    client.disconnect()
    print()

    if msg == None:
        print("User not found. Please check your spelling and try again")
    else:
        if str(msg['uid'])+'\n' in wanted:
            print('{} is already in the wanted list. Models UID is {}'.format(modelName, str(msg['uid'])))
        else:
            f = open(wishlist, 'a')
            f.write(' ')
            f.write(' ')
            f.write("-")
            f.write(' ')
            f.write(str(msg['uid'])+'\n')
            print("{} with UID {} has been added to the list".format(modelName, msg['uid']))
        print()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
    loop.close()

```
