### ISSUE TITLE
Stream is off. (MFC)

### ISSUE THREAD

**Issue by kvluko** [jrudess/streamdvr#7]
Some channel is sometimes not captured. Even though there is a live stream the status is "stream is off.". 

Seems to only happen with a limited number of models but I cant really tell without knowing what should be there.

Its no "on/off"-recording but longer segments or complete days that seem to not be captured.

To rule out any connection issue I tried the streams on the site itself as well as with mfc-node.

Here are profileIDs that I have encountered capturing issues with multiple times so far:
- 18620849
- 19953721
- 25209765

**Comment by SearchAndDestroy** [comment]
I also have this problem with a few (e.g. 21420966). It's working perfectly on MFC itself but it's not always captured. Maybe there is no mobile feed? I haven't checked from my phone.

**Comment by jrudess** [comment]
If you haven't already, try turning off websockets in mfc.yml

    mfcWebSocket: false

Have added the IDs and will see if I can reproduce.

**Comment by lukiluki123** [comment]
Same issue here with this id: 9662139
It's independent from mfcWebSocket value

**Comment by jrudess** [comment]
The latest commit to master branch is an attempt to address this problem, but I have not yet tested it myself.

Node 9.4.0 or newer is required now in master branch, but you can backrev to an older version of MFCAuto in package.json if you need to keep using an older version.  The code should be compatible with either.

**Comment by kvluko** [comment]
Thanks for looking into it, seems to be working so far.

But thats more of a guess right now, the time span was rather short.

I'll give more feedback if I can rule out any missing captures more reliably.

**Comment by jrudess** [comment]
One side affect of the change is that models seem to get stuck  in "Away" state when they are really offline, but not always.  The only affect this has is a wrong status in the site lists (and no "has logged off" printout in the logs).

**Comment by jrudess** [comment]
Having trouble reproducing any 'stuck in away state' issues now, so it may have been a temporary server glitch.  If anyone else is noticing incorrect mfc status, please let me know.

**Comment by jrudess** [comment]
Released in v0.8.0
