### ISSUE TITLE
Streamlink removal of support for sites

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#71]
CB support was removed in https://github.com/streamlink/streamlink/commit/c7bef14b2aed576777cc538ade1fbd2ad4047f08

The chaturbate code can be maintained as a separate streamlink plugin, but it will probably need someone motivated to do it, as I don't have time at the moment.

**Comment by Asynchr0nous** [comment]
looks like its the same case for bongcams and few other sites. not sure what can be done about those plugins but for chaturbate i would suggest using your old plugin script, which without a doubt is much faster. you can still use streamlink since both methods extract the exact same url for stream just differently.

**Comment by SearchAndDestroy** [comment]
You could switch to youtube-dl since it's recording without problems.
However, you may have to use -q instead of -g since I get "WARNING: Unable to download SMIL file: HTTP Error 400: Bad Request" and it doesn't record anything on Mixer at least.
I'll test it on CB.

**Comment by jrudess** [comment]
Ah interesting.  I didn't even think to try youtube-dl.  I'll look into at least switching CB to that.

**Comment by Asynchr0nous** [comment]
the problem with youtube-dl is the files will appear to be perfect but the video/image at times will get stuck at different parts of the video without actually any error whatsoever. I'm speaking this from experience for a different cam site (streamate) but maybe it might be different for chaturbate.

One issue that we will come across with youtube-dl is that it tries to use full bandwidth and not what is required like with ffmpeg.

**Comment by jrudess** [comment]
I'd only be using youtube-dl for fetching the m3u8 link.   Then ffmpeg or streamlink to download still.

**Comment by Asynchr0nous** [comment]
ah right i thought you meant recording using youtube-dl. in that case youtube-dl is a perfect alternative although i'm not sure about performance when the list is big. it should be faster than streamlink though

**Comment by jrudess** [comment]
Changed title since this isn't just CB specific.  

I've moved CB over to using youtubedl for online/m3u8 checks.  Let me know if you think performance is better/worse/same as streamlink was.   My very non-scientific methods put it at slightly better.

**Comment by Asynchr0nous** [comment]
takes approx 2 min to start recording according to the timestamp but also takes approx 2min to remove model. not tried adding any yet.

**Comment by Hampster82** [comment]
I tested it out a bit earlier, performance difference is hard to gauge for sure. There are at least fewer processes fired up during checks now so in theory it's potentially less cpu heavy. In practice, hard to say.

I'm curious though, if you are only using youtube-dl to fetch the m3u8 link, is that not possible with nodejs itself or a nodejs module? Firing up separate processes is never going to be particularly performant, and it would be surprising if nodejs didn't have seemingly simple functionality like that.

**Comment by Asynchr0nous** [comment]
i've been testing this out too. there are few issues i've come across but one of the main one i can think of right now is to do with partial recordings. what i mean by that is that the script may start to record a model but its doesn't actually record the whole session for instance i had a model that cammed for few hours straight yet only 2-3mins were actually recorded even though the whole time it said that "x is already recording". 

This issue happens with youtube-dl front end (v0.10.1 + commits) as well as with streamlink (lastest release version v0.10.1). For both tests, i made sure that ytdl or streamlink was used to fetch m3u8 urls and that ffmpeg is actually used to record (since there are less drops compared to SL in my case)

**Comment by forsomefun2** [comment]
Is anyone camsoda still working. Mine does not record it seems

**Comment by jrudess** [comment]
> I'm curious though, if you are only using youtube-dl to fetch the m3u8 link, is that not possible with nodejs itself or a nodejs module? Firing up separate processes is never going to be particularly performant, and it would be surprising if nodejs didn't have seemingly simple functionality like that.

Yeah a nodejs library for CB like MFCAuto is for MFC would be a superior solution for performance in general.   The primary reason I'm using youtube-dl/streamlink for retrieving m3u8 is to remove that knowledge from this code base.   If there were a maintained nodejs library for CB, it would definitely be an option I could support.

But at the end of the day none of the code in this repo knows how to retrieve m3u8's from any of the sites it supports, or how to even download their streams.  All of that functionality comes from other programs, which makes this repo much more resistant to DMCA or other types of silliness.

**Comment by Hampster82** [comment]
Oh, I was thinking more generic solutions rather than bespoke site specific stuff, but I'm guessing it's just not possible.

**Comment by jrudess** [comment]
backto had some streamlink plugins that attempted to do m3u8 finding in a generic manner.  But every site has a different api for being able to find the m3u8 links if you try to do it using the site's own flow.

**Comment by jrudess** [comment]
Few sites have been removed in v0.11.0:  mfcsl, camsoda and cam4
