### ISSUE TITLE
MFCSL - failing to record with Streamlink

### ISSUE THREAD

**Issue by wearfears** [jrudess/streamdvr#72]
System: Centos 7
Streamlink: 0.14.2+86.g2c9cfe8
Back-to plugins: hlssession and myfreecams
streamdvr: v0.10.1-6-ge461eb2

mfcsl recordings seem to work fine with ffmpeg. However, after setting `streamlink = true` in config.yml in order to use streamlink, recording no longer works; while it detects that the model is online, it simply nevers seems to write to the directory. The following message is repeated in rapid succession for any online models after every recording attempt until it gives up and flags the model as offline:

`[20180901_194124] MFCSL    [ERROR] XFuukaX, XFuukaX_mfcsl_20180901_194122.ts not found in capturing directory, cannot convert to mp4`

Interestingly, streamlink records perfectly fine with CB. I am also able to manually extract mfc m3u8 links via streamlink and play in VLC without much issue.

This would not be much of an issue if ffmpeg recordings were not so choppy--the hope is that streamlink recordings would be better. Any ideas?

**Comment by Asynchr0nous** [comment]
you need to set  the mfcsl plugin to true  as well. if you later tried that you want to move back to using ffmpeg, you will need to set it to false

`super("MFCSL", tui, "https://www.myfreecams.com/#", false, "best");`
TO
`super("MFCSL", tui, "https://www.myfreecams.com/#", true, "best");`

**Comment by wearfears** [comment]
Thanks for the suggestion. Unfortunately, it did not seem to work and I got the same issue. I think I'm okay with just using ffmpeg for now (although even it seems to fail recording in a similar way after running straight for a day or so). Thankfully, I do not have a lot of mfc models to watch.

**Comment by Asynchr0nous** [comment]
i just realised you need the hlssession pluging but i'm not sure about the correct way to install that because as far as i can tell you can only have either hlssession plugin or the current plugin it uses (need to check it) and not both.

**Comment by jrudess** [comment]
I've removed mfcsl.  It was never very stable anyway.   However, I've re-enabled mfc plugin by default by pointing to a branch of mfcauto re-uploaded to github.   It is not the latest version, but I've also created a pull-request to get it updated.
