### ISSUE TITLE
[Plugin Request] Pixiv Sketch

### ISSUE THREAD

**Issue by henao941** [jrudess/streamdvr#76]
Hello, I was wondering if someone could create a plugin for Pixiv Sketch (https://sketch.pixiv.net). This site is already support by streamlink so I thought would be easy to integrate it to streamdvr, but I've failing miserably at it since I don't know the first thing about doing these sorts of things. It be much appreciated if someone could make a plugin for this site.

**Comment by jrudess** [comment]
Sorry for the long delay in replying.  I would look into adding the site, but generally I won't make accounts for websites and this site appears to require a login.

But I should still be able to add the plugin or help you get local mods working with some details.  Can you get streamlink to record manually?  If so, please send me the command line, as that should be all that I need to at least allow you to test and report back with some log output.

**Comment by Asynchr0nous** [comment]
streams are found at `https://sketch.pixiv.net/lives` so command for would be `streamlink https://sketch.pixiv.net/@darifio/lives/8581943091224653020 best`.

login is required to see NFSW streams.

**Comment by jrudess** [comment]
Ahh, great.   Looks easy enough to add then.   streamlink can find the m3u8 just using 
```
https://sketch.pixiv.net/@user/lives
```

Since youtubedl does not work, here's my first reason to finish coding m3u8_streamlink.sh

**Comment by jrudess** [comment]
Support added in master branch.  I've only tested it on a single streamer.
