### ISSUE TITLE
Streamlink - Unable to open URL 

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#77]
Lately i've been getting "Unable to open URL: https://edge110.stream.highwebmedia.com/live-hls/amlst:modelname etc....." errors more frequently even though the model might still be in public chat. the weird thing is that it actually fails to play in browser too when this happens. However, for some another weird reason youtube-dl works when the above fails. 

the problem is youtube-dl is alot slower than streamlink at fetching m3u8 urls. so i was wondering whether it would be possible to use both together in some way e.g. using streamlink by default for fetching and if/when this error occurs make an attempt for JUST that model using youtube-dl. 

i don't know how reliable this method would be but i thing it would best to have an option to disable this method in config file so that the script can be used without new bugs that may occurs. of course that all depends on if its possible and whether it would be implemented or not. either way thanks for this great script

ps. i don;t know what exactly causes this error and is definitely related to the fetching script but one thing i have noticed is that when this error occurs sometimes you can still use streamlink (in new terminal) to play/record that particular model by selecting different stream quality. for instance say best/worst or both fail, it might work fo other available qualities (though not thoroughly tested)

**Comment by jrudess** [comment]
In the current architecture, it is assumed there is only one m3u8 lookup tool for a site, even though I allow multiple capture tools for sites.   However, there is merit to the suggestion to allow multiple m3u8 lookup tools, but I'll need to consider how to implement as I think it would impact the current plugin architecture a bit (new class hierarchies).
