### ISSUE TITLE
back-to/plugins removed with hlssession plugin needed to use streamlink

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#78]
The back-to/plugins repo referenced in the README.md is gone.   I haven't been able to pay attention to this repo or issues for most of the summer.  If anyone knows whether the hlssession plugin simply moved to a new location, or is gone for good, please let me know.  

I do have my copies of the hlssession and myfreecams streamlink plugins and can reupload them to a new repo under my account if needed to keep streamdvr somewhat alive.

**Comment by e2489** [comment]
Yeah, if you could reupload it, that would be great. Not seeing it anywhere...

**Comment by Asynchr0nous** [comment]
The plugins page was completely removed few months back afaik. i have tried looking around to see if it moved to a new url but was unsuccessfull. You could re-upload it if you want to but i feel like your version of the mfc script might be more stable imo (but needs mfcauto, which was also removed)

**Comment by e2489** [comment]
Oh, I didn't realize streamlink was required for CB now. I haven't updated in a while, so I'm a little out of the loop. A re-upload of hlssession would be very much appreciated then.

**Comment by Asynchr0nous** [comment]
you need streamlink/youtube-dl for all the plugins now but hlssession is ONLY require if you enable mfcsl in config

**Comment by jrudess** [comment]
backto has a new 'generic.py' plugin that seems to be working as a replacement for hlssession.py, at least for mfc.  But it needs more testing.   

To try it out just replace "hlssession://" in basicsite.js with "generic://".   Will run with this for a bit and see if I can expose any issues.

**Comment by jrudess** [comment]
FYI, generic.py made it past the infamous 15 minute mark where hls streams were pausing and not recording anything new when using vanilla streamlink.  So it looks like 'generic.py' will be the new replacement for hlssession that was removed.

**Comment by kuchenstrudel** [comment]
Should we test the generic plugin on our own, or will you push it to master soon?

**Comment by jrudess** [comment]
Looks like it's not needed.   I'm running with vanilla streamlink now to capture cb, twitch,  and mixer and all three are working well.  Released in v0.11.0
