### ISSUE TITLE
[Feature Request] Add more control to site folder naming convention

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#8]
I use Plex to organize all my streams and it'd be nice to keep CB/MFC separate from Twitch. It'd be nice to have an option to organize streams by site name as shown below.

Example:

└── CB
&nbsp;&nbsp;&nbsp;&nbsp;└── Streamer Name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;└── Streamer Name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4

└── MFC 
&nbsp;&nbsp;&nbsp;&nbsp;└── Streamer Name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;└── Streamer Name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4

└── Twitch 
&nbsp;&nbsp;&nbsp;&nbsp;└── Streamer Name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;└── Streamer Name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── Streamer-20180122_115638.mp4

Edit: Should have looked harder. Option is already there.

**Comment by clearview1** [comment]
May i ask where you see this option?

**Comment by PurrSevere** [comment]
@clearview1 
I actually had to add some code for this to work as I wanted it to. I don't know if this is the best way to do it but it works for me. 

This all takes place in `site.js`

I added a new variable in the `getCompelteDir` function:
`let siteDirFixed = this.siteDir.substr(1).toUpperCase();`

Then edited the `completeDir` variable here:
`completeDir = completeDir + "/" + siteDirFixed + "/" + streamer.nm;`

Final code should look like this:
![screen shot 2018-03-28 at 11 02 52 am](https://user-images.githubusercontent.com/35707415/38047508-9a7f609c-3277-11e8-8c3a-f26cd90a7dda.png)

**Comment by forsomefun2** [comment]
These changes work great but I think it breaks tui

**Comment by jrudess** [comment]
Ah, this issue got closed before I happened to notice it, so I'm only reading it now.  Since every site has its own yml config file, I think the most configurable way is to move the directory name to that file, and then you can use anything you want.

**Comment by jrudess** [comment]
I've implemented this a little differently locally.   I think it accomplishes what you want though.  There will be a new option ```siteSubdir``` that enables adding the site sub-directory.

```
    async getCompleteDir(streamer) {
        let completeDir = this.tui.config.recording.completeDirectory;

        if (this.tui.config.recording.siteSubdir) {
            completeDir += "/" + this.siteName;
        }
        if (this.tui.config.recording.streamerSubdir) {
            completeDir += "/" + streamer.nm;
            if (this.tui.config.recording.includeSiteInDir) {
                completeDir += this.siteDir;
            }
            try {
                await fs.promises.mkdir(completeDir, {recursive: true});
            } catch (err) {
                this.errMsg(err.toString());
            }
        }

        return completeDir;
    }
```
