### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#80]
I spent some time this morning reworking my personal Docker container to share with you all. 

It includes somewhat up-to-date version of MFCAuto and the latest working  back-to streamlink plugins before they were removed.

I'd like to get jrudess's permission before I post a link to it.

Edit: Released here: https://hub.docker.com/r/purrsevere/streamdvr/

**Comment by jrudess** [comment]
Feel free!

**Comment by Asynchr0nous** [comment]
Excuse my ignorance but how does this differ from using this script? and does it improve performance?

**Comment by Asynchr0nous** [comment]
any update on this? really looking forward to giving it a try. Thanks

**Comment by PurrSevere** [comment]
Sorry about that. I should be able to release this later today.

**Comment by PurrSevere** [comment]
Here's a link to the docker container:
https://hub.docker.com/r/purrsevere/streamdvr/

Let me know if anyone has any questions and I'll do my best to help.

**Comment by Asynchr0nous** [comment]
So its my first experience with docker and if i'm being honest i'm not sure what i expected. I managed to install and run this without any issue but i few questions (probably not the smartest either). 

How does one add/remove models? or config anything for that matter? where is it supposed to save these files?

**Comment by PurrSevere** [comment]
I guess I should have been more thorough in the readme file.

You need to bind mount 3 directories.

1. /capturing -- Where current recordings are saved (Not really needed but I like to see who's capturing via directories not just the log)
2. /captured -- Where converted models are saved
3. /config -- Where streamdvr's configs are saved. You need to get this manually from this repo.

Any changes you make to the mfc_updates.yml, cb_updates.yml etc in /config will then add the model to the capture list.

**Comment by Asynchr0nous** [comment]
Sorry but how do i bidn mount them? I tried this command: 

`docker run -v /volumes/passport\ ultra/scripts/purrsevere/capturing:/capturing -v /volumes/passport\ ultra/scripts/purrsevere/captured:/captured -v /volumes/passport\ ultra/scripts/purrsevere/config:/config  purrsevere/streamdvr
`
but get an error saying:
`are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.`

I tried adding it there but doesn't let me

**Comment by PurrSevere** [comment]
That's correct, but try using a directory in your home folder such as /Users/username and not something in /Volumes/. At least to test. It looks like a permissions problem on MacOS.

**Comment by Asynchr0nous** [comment]
ok this command works:

`docker run -v /Users/admin/purrsevere/capturing:/capturing -v /Users/admin/purrsevere/captured:/captured -v /Users/admin/purrsevere/config:/config  purrsevere/streamdvr
`
now I just need to figure out how to solve the permissions issue

**Comment by PurrSevere** [comment]
It’s because of the uppercase V in Volumes. And Passport Ultra. MacOS is case sensitive.

**Comment by Asynchr0nous** [comment]
programming is weird man. i intially tried that with uppercase but it gave me error saying it needs to be in lower case follow by the error i posted above. anyway the only feedback i have right now is that there is no colour in the debug log

**Comment by PurrSevere** [comment]
You can show colors by adding -it to the docker run command.

This has been the most stable way of recording MFC/CB videos for me by far. ffmpeg works so much more better for me than streamlink. I've been running this for a long time now and have had the issues you mentioned in the past. This is the resulting config after extensive testing.

**Comment by Asynchr0nous** [comment]
Thanks. 

For me ffmpeg is the most stable for CB,Bonga,Cam4 & Streamate. While streamlink is the one thats most stable for MFC (horacio9a's version although its quite out of date now) but the low cpu usage and ability to record no mobile feed models is whats keeping me from moving over. 

Btw what OS are you using to run your docker container. I'm asking because even with just single site enabled with 2 models, the cpu usage for the hyperkit process was around 50-75% on average and reaching as high as 150%. actually just starting the docker application without running any containers shoots my cpu to just over 100%  for like a min while its starting up.

**Comment by PurrSevere** [comment]
This container uses Alpine Linux. The reason CPU jumps up so much is because of streamlink. Streamlink is used to check model online status and it happens to me on all the other OS's I've tried. Is this not normal?

**Comment by Asynchr0nous** [comment]
I know that the cpu usage changes everytime the script refreshes but in this case it seems to high imo. for example in the "normal" version it goes from 0/1% to anything between 7-15% based on number of models in your config.

**Comment by PurrSevere** [comment]
I'll look into it, but it's always been like that for me. Even running it without a container, it still jumps up to 100% CPU.

**Comment by jrudess** [comment]
@PurrSevere if you plan to maintain the docker, I'd be happy to point to it in the README.md.  Let me know if that's alright with you.

**Comment by jrudess** [comment]
It's possible to get the directory structure shown in this issue now with the following settings:
```
  includeSiteInFile: false
  includeSiteInDir: false
  streamerSubdir: true
  siteSubdir: true
```
