### ISSUE TITLE
Problem starting streamdvr.js

### ISSUE THREAD

**Issue by Alexo88** [jrudess/streamdvr#81]
Hello friends, I hope you are well.
I have problem when I start the streamdvr.js
I see this error

---------------------------
Windows Script Host
---------------------------
Script: C: \ Portable SSD \ MFC tools \ streamdvr \ streamdvr.js
Line: 5
Character: 1
Error: Syntax error
Code: 800A03EA
Source: Microsoft JScript compilation error

//

There is line 5:
const Promise = require ("bluebird");

I do not know how to fix it, I hope someone gives me a clue.
I appreciate the community.

**Comment by Asynchr0nous** [comment]
Also by looks of it, it seems like you're NOT using nodejs to run this script. are your sure you followed the instruction on how to use tis script?

can you copy/paste the exact error you're getting from terminal/command prompt including what command you used. if you didnt edit the script it should work straight away (after installing the necessary tools).

**Comment by Alexo88** [comment]
> it seems like you're NOT using nodejs to run this script. are your sure you followed the instruction on how to use tis script?
> 
> can you copy/paste the exact error you're getting from terminal/command prompt including what command you used. if you didnt edit the script it should work straight away (after installing the necessary tools).

Good day.

I think I followed these steps

Install the node.js
I have the GIT in portable version
download the .zip and unzip in one direction.

Use git to install streamdvr
First I opened GIT
cd C: \ Portable SSD \ MFC tools \ streamdvr
next
apn install

I did not see problems in the installation, although I am new to this.

open the node.js prompt
and wrote
CD C: \ Portable SSD \ MFC tools \ streamdvr
and followed
streamdvr.js

I got an alert window with that message I posted above.

That was all I did.

**Comment by Asynchr0nous** [comment]
I don't use windows but after you after you do `cd C: \ Portable SSD \ MFC tools \ streamdvr`
it should be followed by `npm install`

To run:
`node streamdvr.js`
