### ISSUE TITLE
MFC.yml doesn't get updated

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#82]
when adding a new model, the file mfc.yml file containing list of all models doesn't get updated which means it only records for that session (btw tui is disabled). Removing models seems to work fine for most part (99.9%, 1% givng error it doesn't exisit even if it does). Not sure why its doing this or whether it existed before because I usually have this disabled but was testing something out today. usually after adding or removing a model, its followed by `rewriting sitename.yml` but in this case its just `modelName added to capture list`

i tested this on 3 different versions; the latest version, commit from Sep 23 and finally purrsevere's docker which is based on the latest version/commit. its updating for other sites though.

**Comment by PurrSevere** [comment]
Can confirm. Not sure when it stopped working. I currently have over 100 models and adding new ones starts capturing them but never updates the mfc.yml file. Will test in different environments soon.

**Comment by PurrSevere** [comment]
Narrowed it down. 

This issue was introduced in commit b6fc89c.

Removing `this.dirty = false;` from the mfc.js file fixes the problem but I honestly don't know why or what that line of code does. 

Maybe @jrudess can comment on this.

**Comment by Asynchr0nous** [comment]
Damn that was quick and yeah i wonder what that actually does since i see that quite often.

**Comment by PurrSevere** [comment]
So when that line is removed it causes the text `Rewriting ./config/mfc.yml` to endlessly display every time streamdvr scans for model status. This won't happen if debug is set to off but I always have it on. 

Another thing that happens is the file `mfc_updates.yml`never gets restored to its original state. The name of the model to include/exclude stays there.

![screen shot 2018-11-15 at 12 19 47 pm](https://user-images.githubusercontent.com/35707415/48580468-29651000-e8d4-11e8-9052-656e3649ec53.png)

**Comment by Asynchr0nous** [comment]
similar issue exists if a model does not have mobile feed but instead it prints an error along the lines of `Recording started for model X`  followed by `not found in capturing directory, cannot convert to mp4 error` EVERY second

**Comment by PurrSevere** [comment]
That's an unrelated issue. MFCAuto requires that the model have mobile feed enabled in order to record.

**Comment by Asynchr0nous** [comment]
what i'm trying to say it that if a model doesn't have mobile feed then it should make an attempt to record (which is handled by this script)

**Comment by PurrSevere** [comment]
Ah yes, that issue is quite annoying and agree that it should be handled differently.

**Comment by jrudess** [comment]
Yeah this is the same issue as https://github.com/jrudess/streamdvr/issues/68

The work around is to type "add mfc name" twice in the console (or "remove mfc name").  First time will add to local list, 2nd time will give you an error, but it will actually write the file.  I have some kind of dumb threading bug that is unique to mfc because of the differences in how communication with mfcauto works vs other plugins.  But since I found a workaround, I've been too busy to fix it properly.
