### ISSUE TITLE
Problems with capping new mfc streams

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#83]
Got this report from a chat room.   Potential fix is to add  -map 0:1 -map 0:2 to the ffmpeg arguments in order to handle new ts streams.  But this may break flv stream models not using HLS and needs testing.  

If you run into any models not capturing properly, please try adding these to the ffmpeg arguments and let me know.

**Comment by Asynchr0nous** [comment]
what is this new issue you speak of?

**Comment by PurrSevere** [comment]
Been testing since you posted and no issues so far. 👍 Was going to post a new issue about this but you beat me to it.

**Comment by jrudess** [comment]
Some more info:  

mfc streams are being upscaled to 1280x960, this is causing large cap sizes and terrible quality video, especially with low bandwidth 320x240 streams. the fix selects the first stream from the m3u8 file, which is the actual broadcast stream.

The fix should only be used on mfc caps.  If the fix is used on chaturbate caps, it will automatically select the lowest quality stream, since they structure their m3u8 files differently.

**Comment by PurrSevere** [comment]
Spoke too soon. Seems to be happening randomly to some models still.

**Comment by jrudess** [comment]
I'm also unsure what is going on on the streamlink side when using it to cap instead of ffmpeg.  It may also be selecting the 'upscaled' m3u8 entries.

**Comment by Asynchr0nous** [comment]
This is literally the exact issue i've been having. I have 1 hour recording of a model from other day and its like 4.5GB in size

**Comment by Asynchr0nous** [comment]
I just check all my recordings from yesterday and all of them are 960p and apart from their size being alot bigger than usual the quality of the streams if pretty much perfect

**Comment by Asynchr0nous** [comment]
usually there is only 240p stream available or one other one but now it seems like there are multiples including what it should be. test it with this live model: `streamlink http://video776.myfreecams.com:1935/NxServer/ngrp:mfc_117988279.f4v_mobile/playlist.m3u8?HappyEndings_`

**Comment by jrudess** [comment]
Something like the following in getCaptureArguments, ffmpeg section, should work if you only cap MFC for now.

            if (url.indexOf("==") === -1) {
                params.push("-map");
                params.push("0:1");
                params.push("-map");
                params.push("0:2");
            }

**Comment by jrudess** [comment]
Planned long-term fix is to move these params to plugins/mfc.js and change core/site.js to take new optional argument input to getCaptureArguments for merging in plugin specific options.

**Comment by jrudess** [comment]
A new commit on master branch should resolve this issue for MFC + ffmpeg.  I've confirmed that streamlink captures are still getting the 1280x960 feeds and it is not fixed yet.

**Comment by Parsnip** [comment]
Yah I noticed the big caps a little bit ago, good to see a fix up already.

**Comment by Hampster82** [comment]
Oh so this is what was happening, I was wondering why so many of the caps were 1280x960.

**Comment by Hampster82** [comment]
This seems to be working as expected. 👍

**Comment by jrudess** [comment]
Had one report of a stream that required map 0:0/0:1 instead of 0:1/0:2.   Don't yet know if it's a one-off issue or there are certain feed settings that may require some extra detection logic to get the mapping right.

**Comment by Asynchr0nous** [comment]
> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1352020,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=640x480
chunklist_w723092472_b1352020.m3u8?BirthdayMel
#EXT-X-STREAM-INF:BANDWIDTH=614000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=320x240
chunklist_w723092472_b564000.m3u8?BirthdayMel
#EXT-X-STREAM-INF:BANDWIDTH=5564000,CODECS="avc1.66.50,mp4a.40.2",RESOLUTION=1280x960
chunklist_w723092472_b5064000.m3u8?BirthdayMel

using the above example how would the the result differ if you used map 0:0/0:1 instead of 0:1/0:2?

**Comment by jrudess** [comment]
I don't know the decoder ring for map either, and got the solution and this report in a chat room, but I'll ask.

I don't have a solution yet when using streamlink to record instead of ffmpeg, and the 960p stream is always recorded.

**Comment by jrudess** [comment]
@sassynchr0nous thanks.  Did just that from mfc.js  Streamlink recordings are now getting the 800x600 streams.
