### ISSUE TITLE
Constant errors when a mfc model has no mobile feed

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#84]
I thought I might as well create a new issue instead of talking about it in the other thread.
Anyways for those that don't know currently if a model doesnt have mobile feed (can't record them) the script outputs error messages EVERY second. I think it shouldn't make an attempt to record if this happens or it should give this error when it refreshes similar to how it is for all other sites supported by this script.

That being said if jdrudess or anyone else is able to find a way to detect non-mobile feed models or if MFCAuto has this capability built-in then it would be great to either either just print a message saying "model has no mobile feed can't record" or better yet use different program to handle that specifc model. I currently use MFCDump which only needs model name and it starts recording any and every mfc model (though quality for those streams tends to be 240p). I can upload it you're interested (for windows, mac, linux)(32/64bit). it all boils down to having a mechansim to detect non-mobile feeds or failed attempt at recording.

ps. mostly likely you might have fixed above issue in latest commits but i've not tested it yet. downloading it now actually

Edit: i've never used mfcdump for normal feeds so thought i'd try. it actually records at the available resolution (real) and doesn't use 960p

**Comment by jrudess** [comment]
I thought I had pieced together code for detecting this at some point.  Its possible I lost that when I switched to mfcauto for creating the URLs.

**Comment by Asynchr0nous** [comment]
horacio9a implementation has this line of code to detect no mobile feed models:
` if ((model.camserv) < 840) {printDebugMsg(colors.green(model.nm) + (colors.cyan(' is NO MOBILE FEED - Exclude or Delete!')));return;} // resolve immediately`

its not 100% accurate but works most of the time. looking at mfcauto's code and its seems like you can access the camserv property through bestSession

**Comment by jrudess** [comment]
Yeah, I'm pretty sure I got my solution from reading horacia9a's code.  I swear I had that camserv check in the code base once upon a time, but maybe I'm only remembering that I thought I should add it. :-)
