### ISSUE TITLE
TypeError: this[site].Plugin is not a constructor (+ others errors)

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#85]
upgraded to lastest version and i'm getting the above error when enabling CB. Tried enabling other sites and got these errors:

Bonga: `Cannot find module './plugins/bonga'` just a typo so just needs changing to correct name in streamdvr.js or just rename the plugin to bonga.

Camsoda (i don't use this) but got this error: `kateyjlil error: Unable to validate JSON` tried it with other random models and it just says error and prints out the whole json. 

others seem to be working fine as far as i can tell in this quick test

node version 11.2.0

Update: I was getting the `Plugin is not a constructor` because of an error from my end. i replaced the cb plugin to use streamlink and forgot to change `exports.Cb = Cb` to `exports.Plugin = Cb;`

**Comment by jrudess** [comment]
bongacams issue fixed (but I couldn't test because pfblockerng is blocking bongacams at my firewall so I have to track down the rule and remove it :-)

I'm not able to reproduce the CB error.  Can you paste the full stacktrace if there is one?  May need to turn tui off in config.yml to see it/

**Comment by jrudess** [comment]
Ah, sorry I missed your update for the Plugin error.  

I'll look into camsoda a bit more once I have time off for holidays, but I suspect it was probably broken before the updates.

**Comment by jrudess** [comment]
I think streamlink is still working for me because I'm on an old branch and haven't updated it in a while once I saw that they were removing lots of stuff in the newer commits.

I've been debating maintaining a fork of streamlink that adds back in the things they took that streamdvr needs, or alternatively adding the streamlink plugins needed into streamdvr itself (need to look up how backto was licensing the code).

**Comment by jrudess** [comment]
got it

**Comment by jrudess** [comment]
I am removing support for camsoda but am not deleting any code, just commenting out the plugin loading portion in streamdvr.js).   They've definitely changed the site, and the streamlink plugin would need to be updated to support the changes.
