### ISSUE TITLE
Script errors when captured file isn't found for post processing

### ISSUE THREAD

**Issue by Hampster82** [jrudess/streamdvr#87]
Does that subject make sense? I don't think this happened before but I can't pinpoint when exactly it started. I've noticed this happen occasionally when a streamer starts and stops for any reason in a quick fashion, before a file is created. Windows 10, MFCAuto 5.2.2, in case that matters.

>[2018-11-21-18-58-15] MFC      Streamer recording started (Streamer_2018-11-21-18-58-15.ts)
Trace: [2018-11-21-18-58-17] MFC      [ERROR] Streamer, Streamer_2018-11-21-18-58-15.ts not found in capturing directory, cannot convert to mkv
    at Tui.log (D:\streamdvr-master\core\tui.js:221:21)
    at Mfc.msg (D:\streamdvr-master\core\site.js:499:18)
    at Mfc.errMsg (D:\streamdvr-master\core\site.js:503:14)
    at fs.stat (D:\streamdvr-master\core\site.js:378:30)
    at FSReqCallback.oncomplete (fs.js:161:21)

Easy to reproduce on my end at least, just start the script, wait for a few seconds so that the window says *Streamer recording started (Streamer_2018-11-21-18-58-15.ts)* and then hit ctrl+c on the window to start the exit procedures. 

In normal conditions it doesn't seem like the script dies or anything of the sort, it just errors, but continues and seems to work just fine when the streamer comes back online and the next recording starts.

**Comment by Asynchr0nous** [comment]
So what is the problem? its normal for it to do that but in the lastest version it gives more debug information than before

**Comment by Hampster82** [comment]
It would be normal if it was just *[2018-11-21-18-58-17] MFC [ERROR] Streamer, Streamer_2018-11-21-18-58-15.ts not found in capturing directory, cannot convert to mkv*, that's an expected event that has been written to steamdvr and handled as designed.

But the rest are script errors that nodejs throws. It's not critical since it doesn't halt the script, but these kind of errors are not really be *normal*.

**Comment by jrudess** [comment]
Yeah, this is a generic error in the post-process logic and it just means that the capture process didn't generate any output file.  So if you ctrl+c right after starting the caps, then usually this error should fire.

If it's happening a lot, then I would recommend setting 'debugrecorder: true' in config.yml and then every capture will generate a filename.log file in the streamdvr directory where you can look for any ffmpeg/streamlink related errors.

The addition of the full code trace is a new addition, but it is only enabled when the TUI is off for debug purposes.  If you guys find that annoying, I can make it a config switch so its not there by default.
https://github.com/jrudess/streamdvr/blob/02d8078757f900fa06e166f5583ff24162baa6fe/core/tui.js#L214-L221

**Comment by jrudess** [comment]
Yeah, the trace can be a bit annoying.  Will wrap it in a config option that is off by default.

**Comment by Asynchr0nous** [comment]
I just remembered, if you're using youtube-dl to fetch stream urls then these errors are alot more frequent. it even fails to move files alot more too.

source: ran test for more than 24hours running both streamlink and youtube as front end

**Comment by jrudess** [comment]
Ah, good data point.   With the latest streamlink and back-to's 'generic.py' plugin, streamlink appears to work for CB, so it can be switched off of youtube-dl.

i.e., the following works:
streamlink --stream-url https://chaturbate.com best

**Comment by jrudess** [comment]
```errortrace: true``` in ```config.yml``` to enable traces for all error messages with v0.11.0

**Comment by jrudess** [comment]
It is now optional which m3u8 fetcher is used for CB, mixer, or twitch.  The default is ```scripts/m3u8_youtubedl.sh```, but if you find streamlink more reliable then you can change it to ```scripts/m3u8_streamlink.sh``` in the appropriate site.yml file.
