### ISSUE TITLE
Global Config and per site settings

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#89]
what are you thoughts on moving some of the settings from the global config file to sites .yml? I feel like it would give you more control over how you want to use a certain site. 

For example models that cam on cb/mfc tend to come online more often which means you can set the interval time on the lower side whereas you got site like bonga where some models don't come online for day or weeks which means you don't need to refresh as often. 

Another situation I came across is the lack of ability to choose what recording program to use for each site. as of right now, its either streamlink for sites or ffmpeg for all sites. it would be great to use scriptX to fetch but use programY to record. e.g. ffmpeg for cb but streamlink for say mfc and vice versa.

these were just few examples but making everything independent means it will be easier to handle things in the future and also allow you to add site specifc features better

**Comment by jrudess** [comment]
Yes, more settings need to move to the site files, and a per-site delay should be straightforward to add.  

Both the m3u8 lookup tool, and the recording tool should be configurable per site, but I'll track that in a different issue as it's a much more extensive change to the code-base.  Currently each site extends from a specific recorder class, so that has to be redone and the recorder separated from the site logic.

Within config.yml it can also be more hierarchical so that it's easier to read.  e.g.
```
colors:
    name: magenta
    state: yellow
    offline: blue
```

**Comment by jrudess** [comment]
Take a look at the new format and locations of settings and let me know what else you'd like to be per-site.   Some of the recording options might make sense to be per-site, or possibly all of them.   But at the same time I don't want configuration overload, where you have to change the same setting in a dozen different plugin yml files.

**Comment by Asynchr0nous** [comment]
I think the site enabling should be moved to the site.yml. makes more sense since its site specific. you could also combine tui and listshown into one category (interface). 

`Interface: 
  tui: false
  listshown: false
Colors:
  name: magenta
  state: yellow
  offline: blue
  file: green
  time: grey
  site: green
  debug: yellow
  error: red
Recording:
  autoConvertType:
  captureDirectory: capturing
  completeDirectory: captured
  dateFormat: YYYYMMDD_HHmmss
  includeSiteInFile: false
  includeSiteInDir: false
  streamerSubdir: true
  streamlink: false
  keepTsFile: true
  minSize: 0
  maxSize: 0
Proxy:
  enable: false
  server: socks5://127.0.0.1:1080`

**Comment by Asynchr0nous** [comment]
I think the site enabling should be moved to the site.yml. makes more sense since its site specific. you could also combine tui and listshown into one category (interface). 

> - Interface: 
>     -   tui: false
>     -   listshown: false
> - Colors:
>     -   name: magenta
>     -   state: yellow
>     -   offline: blue
>     -   file: green
>     -   time: grey
>     -   site: green
>     -   debug: yellow
>     -   error: red
> - Recording:
>     -   autoConvertType:
>     -   captureDirectory: capturing
>     -   completeDirectory: captured
>     -   dateFormat: YYYYMMDD_HHmmss
>     -   includeSiteInFile: false
>     -   includeSiteInDir: false
>     -   streamerSubdir: true
>     -   streamlink: false
>     -   keepTsFile: true
>     -   minSize: 0
>     -   maxSize: 0
> - Proxy:
>     -   enable: false
>     -   server: socks5://127.0.0.1:1080

**Comment by Asynchr0nous** [comment]
I'm slight confused about:

> - Debug:
>     -   log: false
>     -   recorder: true
>     -   errortrace: true
> 
> - log:
>     -   enable: false
>     -   append: false
>     -   shown: true

i think it can be simplified to:

**Comment by Asynchr0nous** [comment]
Few more points:
I know you disabled cam4 but left the option to enable it by uncommenting the section in "streamdvr.js". well it doesn't enable (construct) it even after adding `CAM4: true` in config.yml. 

I can't seem to record using ffmpeg with the new structure for the plugins (that rely on streamlink). i noticed that this line of code `super("BONGA", tui, "https://bongacams.com/", true, "best");` has been changed to `super(name, tui, "best");` which means I cant change the option to false (not sure where its been move)

**Comment by jrudess** [comment]
Moving the enables to the site yml is possible.   It will slightly change the definition of what 'enabled' means however.

Currently the plugins only load their config after they are created, and the enable prevents them from getting created.  This helps in the case of a missing library (e.g. mfcauto) because creating it causes errors.

Having the enable in the site.yml means the plugin has to be created.   But that doesn't mean I can't solve the missing library problem differently to prevent errors.  It seems feasible.

As for confusing params, I agree. I need to just write a man page, but have been to lazy to learn man format. :-)

```
debug:
   log: true   # Enables [DEBUG] messages to print for debug
   recorder: true # Enables ffmpeg or streamlink logs to dump to filename.log in the streamdvr directory 
   errortrace: causes [ERROR] messages to also dump a code stack trace
log:
   enable: true # save streamdvr output to streamdvr.log
   append: true # don't overwrite previous output, just append to the file
   shown: true # in tui mode, setting this to false hides the log and only shows the streamer list
```

I probably I should make one more annoying and breaking edit to the config file and move the log-shown and list-shown options to a tui section for better consistency:
```
tui:
   enable: false
   logshown: true
   listshown: true
```

Thanks for all the reports of things I broke.  Been working my way through testing some of them.  Will switch back to immediately and get that resolved.  Recordings seem to be moving for me okay, but I'm using streamlink to record.

**Comment by jrudess** [comment]
I haven't been able to replicate any recording issues using ffmpeg with mfc.

**Comment by Asynchr0nous** [comment]
> Having the enable in the site.yml means the plugin has to be created. But that doesn't mean I can't solve the missing library problem differently to prevent errors. It seems feasible.

In this case you should keep it the way it is and just rename "enable" in config to "sites".

> Will switch back to ffmpeg immediately and get that resolved.

so it was disabled or there is a bug?

> Recordings seem to be moving for me okay, but I'm using streamlink to record.

maybe i need to tweak something on my end but i will try it again and run test for few hours

**Comment by Asynchr0nous** [comment]
> I haven't been able to replicate any recording issues using ffmpeg with mfc.

i didn't try it with mfc yet, that should work since its not relying on youtube-dl or streamlink. with your previous versions i had to change one of parameters to false for all streamlink/youtube-dl plugins to make it record using ffmpeg. not sure what the intended purpose of that parameter was though. (referring to the text in bold, shown below):

`super("BONGA", tui, "https://bongacams.com/", **true**, "best");`

**Comment by Asynchr0nous** [comment]
I think the format for mfc.yml can be improved too. it should store model name along with the uid, as it will be extremely helpful when removing models (currently you only find out which model has been removed after the fact). it won't be used for anything other than for this purpose. 

> streamers:
> - uid: 867823
>        nm: model1

**Comment by Asynchr0nous** [comment]
I think the format for mfc.yml can be improved too. it should store model name along with the uid, as it will be extremely helpful when removing models (currently you only find out which model has been removed after the fact). it won't be used for anything other than for this purpose. 

streamers:
  *- uid: 75867989
   * nm: model

**Comment by Asynchr0nous** [comment]
'''super("siteName",tui, "siteUrl", **true**, "best");'''

**Comment by Asynchr0nous** [comment]
`
super("siteName",tui, "siteUrl", **true**, "best");
`

**Comment by jrudess** [comment]
Storing the model name would be very useful.  Currently all sites share the same site-config loading code for the 'streamers' option, so this change would also cause CB to look like:

```
streamers:
   - uid: modelname
     nm: modelname
```

**Comment by jrudess** [comment]
The streamlink option has now been removed from config.yml, and a new option is in each site.yml:
```
recorder: ffmpeg
```
```
recorder: streamlink
```

**Comment by Asynchr0nous** [comment]
HELL YES!
