### ISSUE TITLE
[Feature Request] Possible to add Mixer?

### ISSUE THREAD

**Issue by SearchAndDestroy** [jrudess/streamdvr#9]
Would it be possible to add the stream platform Mixer?
It seems to be supported by the latest version of youtube-dl (2018.01.21) so it should not be a problem.
I had a few instances where the VOD was not saved or was incomplete when the stream crashed .
Thanks

**Comment by jrudess** [comment]
The primary thing that has to be figured out is how to tell when the person is online vs offline. Once that method is understood, then everything else should just fall into place, especially if youtube-dl already has support.

Twitch has an API for scripts to use to query an account, so it was relatively easy to detect when someone was streaming or not.

**Comment by jrudess** [comment]
I've added mixer support in master branch but have not yet tagged a new release.  Please try it out and let me know if you run into any issues.

**Comment by SearchAndDestroy** [comment]
Thank you :) I'll test it asap and let you know if there are any issues.

**Comment by SearchAndDestroy** [comment]
I think it's working very well. I have zero issues. I tested with a long (7h+ and 9Gb of recording) stream and it recorded it without any problem. Idem with a stream yesterday, it recorded it perfectly :)

**Comment by jrudess** [comment]
Pushed some error-handling cleanup for mixer and marking this one as closed.  Please open new issues if you see any problems.   Will push into a release tag after it runs for a few more days with no issues on my end.
