### ISSUE TITLE
Error while moving a finished recording

### ISSUE THREAD

**Issue by SearchAndDestroy** [jrudess/streamdvr#92]
I'm getting errors moving a recording:
```
[ERROR] Model_cb_20181123-140025: Error: ENOENT: no such file or directory, rename 'V:\streamdvr\undefined\Model_cb_20181123-140025.ts' -> '\\NAS\Share\Final\Directory\Model_cb_20181123-140025.ts'
```
The recording is fine, it's just the postprocessing.
Note the "undefined" in the 1st path instead of the path taken from "captureDirectory".
It was perfectly working before all the modifs for the config files.

It may be only for the 1st recording of the model.

**Comment by Asynchr0nous** [comment]
I mentioned this here https://github.com/jrudess/streamdvr/issues/89

**Comment by wearfears** [comment]
Same issue here with mfc recordings--happened for all files recorded overnight.

**Comment by jrudess** [comment]
Looks like I busted every site (except MFC) with ffmpeg.   If you switch to streamlink, it should work, but streamlink will have the large cap size 960p resolution issue with mfc.

**Comment by SearchAndDestroy** [comment]
I think the issue is that you should have ```this.tui.config.recording.captureDirectory``` in lines 463 and 464 of core/site.js.
You forgot the ".recording." part :)

**Comment by jrudess** [comment]
ahhh damn.  I always forget to shut off mp4/mkv conversion in my test cases.  Thanks for catching that.

**Comment by PurrSevere** [comment]
This is still happening to me even on the latest commit. Happens on CB and MFC. Converted files are fine but the error message is still there. 

![screen shot 2018-11-30 at 9 50 55 am](https://user-images.githubusercontent.com/35707415/49305908-81c81000-f485-11e8-83f9-5e4631cc529e.png)
