### ISSUE TITLE
Unable to record CB with ffmpeg with latest streamdvr

### ISSUE THREAD

**Issue by wearfears** [jrudess/streamdvr#93]
System: Centos 7
Streamlink: 0.14.2+86.g2c9cfe8
Back-to plugins: generic
streamdvr: 0.11.0

I get the following error when recording CB with ffmpeg:
```
[20181123_104133] CB       <model> recording started (<model>_cb_20181123_100821.ts)
[20181123_100822] CB       [ERROR] <model>, <model>_cb_20181123_100821.ts not found in capturing directory, cannot convert to mp4
```
This happens rapidly and immediately after it attempts to begin recording any online model and will continuing doing this until I force stop it. Files do not seem to every be created in the capturing directory. CB seems to work fine when I switch back to an older build of streamdvr or with the current streamdvr build + streamlink. But streamlink has the issue of stopping recording after it reaches a range of sizes. From what I've seen so far, this seems hang when the file reaches anywhere between 1 to 2 GB, which makes ffmpeg considerably more preferable. 

Recording with ffmpeg also generally seems to work fine for MFC on the latest streamdvr build (save for the file moving into 'captured'  directory issue).

config.yml:
```
enable:
  MFC: false
  CB: true
  Twitch: false
  Mixer: false
  Bonga: false
  FC2: false
recording:
  autoConvertType: mp4
  captureDirectory: /stream/capturing-cb
  completeDirectory: /stream/captured-cb
  dateFormat: YYYYMMDD_HHmmss
  includeSiteInFile: true
  includeSiteInDir: true
  streamerSubdir: true
  streamlink: false
  keepTsFile: false
  minSize: 0
  maxSize: 0
log:
  enable: true
  append: true
tui:
  enable: true
  logshown: true
  listshown: true
colors:
  name: magenta
  state: yellow
  offline: blue
  file: green
  time: grey
  site: green
  debug: yellow
  error: red
proxy:
  enable: false
  server: socks5://127.0.0.1:1080
debug:
  log: false
  recorder: false
  errortrace: false
```
cb.yml
```
siteUrl: "https://www.chaturbate.com/"
scanInterval: 100
batchSize: 5
```

**Comment by jrudess** [comment]
Looks like the problem is only when ffmpeg is used to cap, and not streamlink.  In debug

**Comment by jrudess** [comment]
Looks like a change I made to keep streamlink working is what busted ffmpeg.   My current repo area is in the middle of rewriting the code to switch youtubedl/streamlink/ffmpeg handling into shell scripts, so fix will take most of the day.   

I believe that 49e2287ae0cfffd5f4f87ed2b1dabb859895270b should be a safe commit to use.

**Comment by jrudess** [comment]
For the brave, the new bash flow is implemented for youtube-dl for CB, Mixer, and Twitch.  Both sites should now be functional using either streamlink or ffmpeg to record in top-of-tree.

But youtube-dl is the only written script for m3u8 lookup at the moment.

**Comment by jrudess** [comment]
Please try 0.11.1

**Comment by jrudess** [comment]
Note that 0.11.1 adds a new option into cb.yml  ```m3u8fetch: scripts/youtubedl.sh```
