### ISSUE TITLE
Lists of lookup errors to filter

### ISSUE THREAD

**Issue by jrudess** [jrudess/streamdvr#95]
Starting this issue to report any new errors you see showing up on a periodic basis in the log.   Some of these used to be filtered, but I relaxed the old filters I had since it's been a while since I've reviewed them.

I've only seen this one once with CB.  Looks like ther server didn't respond to a streamlink lookup.
```
[ERROR] error: Unable to open URL: https://chaturbate.com/modelname (HTTPSConnectionPool(host='chaturbate.com', port=443): Read timed out. (read timeout=20.0))
```

**Comment by Asynchr0nous** [comment]
i get that error sometimes (in bulk) and its generally when chaturbate is having some issue on their end. youtube-dl is more reliable in terms of actually extracting m3u8 urls even when chaturbate is messing up but this script is more prone to errors with it for me (generally speaking)
